apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  releaseName: harbor
  chart:
    spec:
      chart: harbor
      version: 1.19.2
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: harbor
  interval: 30m
  install:
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: StatefulSet
              name: harbor-database
            patch: |
              apiVersion: apps/v1
              kind: StatefulSet
              metadata:
                name: harbor-database
              spec:
                template:
                  spec:
                    initContainers:
                      - name: data-permissions-ensurer
                        resources:
                          requests:
                            memory: 16Mi
                          limits:
                            memory: 16Mi
  valuesFrom:
    - kind: ConfigMap
      name: harbor-public-values
    - kind: Secret
      name: harbor-values
