apiVersion: v1
kind: Secret
metadata:
    name: harbor-bootstrap
    namespace: harbor
type: Opaque
stringData:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:6wWbIjteCOw=,iv:ed5wEMEma0Xs/CFSV5TZc9EvmieczF8UDQzt+eaLip0=,tag:/pV8Y6RT/aVUbzF8PXD/ug==,type:str]
    secretKey: ENC[AES256_GCM,data:PPnqQl6bODCH/PwdYy82WA==,iv:Vpuj9z/HqA4kpj+Cg121W4+Jy1FpYZvMC2tRTTI+vdg=,tag:QGz/2W6f/lzJkEWct0cxAQ==,type:str]
sops:
    lastmodified: "2026-09-18T18:31:05Z"
    mac: ENC[AES256_GCM,data:EDNYWp0484+ASSM1CjC6LrYxysUa9iJiV3kVZc3PThB4dhk0eCLTmv3HNpyO95/CvVB6QzXFv1Zy2RYCpV9Ow8sGLjAAmIdbj7DgqH8GWN0uJLxP9L6kbUyTDidsM52qmN9LELyWmY+l8cjtkBdzeQDZJdUQqW60mx+yJYzclQk=,iv:2Lh330j0ulAEbuntIILkV3ecTfS3j+nbWrEkC9rnKVE=,tag:NqZ9kyo+2k1joy7a9Np8Bg==,type:str]
    pgp:
        - created_at: "2026-09-18T18:30:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XAQ//VRxcb13DjrJwWjioNRseCV9WW8aaP5x9BA+4IFYzuvvs
            jRufeqgc1KUEx36FsBGywmqt86r8vr/wUlv5WctObmSq2++AGWbm/fq4CnKIo7ts
            4BnjKGaw20chKrXkXr+PqUSDsHXE554QDAiSMPGZsmJbCXSd8bR3uiE0P5Tg3LcZ
            5YjDqX7/6SpmWFknI6JQEbNkWSFT7yUyrJp9UUrfQvVrgB+uipvICofDLPnH5vl3
            mzfWRu77/eYrNspYEAy3PktUlxpFD5cFFENp2eUppdk5CMykUA2BIyYbCyP35Et2
            arYBiyVLgxGy6oJsrUMrhE56rag8Flk3goQS6BucYAlxSyzcR1JRcVTCPaaDSpTi
            pCB4UlTT5ymOT7PGt4NyK7r8U9B6vyXTZZ2CrroWuHR7K2xpq0IqUxKHlxUB2B8P
            3R5WHiR2q8J6L8tzonZI11noUxbTRY2SW2jB0xOpgGgQeG/ZAG5qVnInFR+EYAz3
            UjqChhe46qtywVKVeSDNotWhGVnSkYypNi5LsqT2Bo4pTWw1aazEbi1TrzdvUoUm
            9C6z2ZwemD1buwPg9QClzerQfHQrsn8u8KQQ9ed/0BJHUs96HgMnLBjSnOMgK3KK
            5XeLeT3AMbTynIC3C8eCeU/wF6WT/FwR/yBIfDDEOOIBcY5vrLosTc34+SJ2mYzU
            aAEJAhBPQTsA/lVpXSN8d2rAKTFcc3tO3m4H/qY1SvL6IMInfv66LWklYQ6iMNHQ
            11KpJ1oJNuF+xqPWsiO+VgpEjtbdouNlkS08yrv6zY1HbbRkxk75cQ2Iyl1Q47EI
            STsvq2pIHkF+
            =1D4H
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
