---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goatcounter-tools
  namespace: goatcounter
  annotations:
    volume.kubernetes.io/selected-node: brenno-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
