apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: goatcounter-log-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: goatcounter-log-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: goatcounter-log-reader
subjects:
  - kind: ServiceAccount
    name: goatcounter-log-importer
    namespace: goatcounter
