apiVersion: v1
kind: Secret
metadata:
    name: goatcounter-api
    namespace: goatcounter
type: Opaque
stringData:
    GOATCOUNTER_API_KEY: ENC[AES256_GCM,data:W8rk31R9DuQYnY0QB4HIZvVxIze4SWR33rMqz5r+uFuvCH2YAi1CiOcsY4dJDwSQNzE=,iv:/dOvrrGOCQvFDw3SRhELQ+tAQjjhRA4ZWkp827vanrk=,tag:H9kZhM3lmx8zBnLzTsiQFA==,type:str]
sops:
    lastmodified: "2026-02-25T03:29:39Z"
    mac: ENC[AES256_GCM,data:hlfc7HctMUNqxF8zLxX2lLcQ8ZnYsEQasD5JVzy6oHmFaJsNTvDBtpsGcdEQOteP/24qKYpotK8chNh11k+BXrD2/rc+7VBwl2isjFdKVEpHh1um8kNnu7yM4pfBuecv7vAvf7WsDUjcilYphR+ku8GiDy2+U7Vcf9fJzC9woAU=,iv:xb1fccgDZ378iEZKIoyFCdkv35pdn/yBkGC6cAbClBk=,tag:4opqwTF7oHvBZMH0yj4mnQ==,type:str]
    pgp:
        - created_at: "2026-02-25T03:29:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XAQ/9Gd8HnCidnWVM3ujcdHM9TtWk2jdShW4T2BmfhWSkCICN
            rjLyv59+PFCDwL3dCv/YmW++3iwWUBqNzXvscOiOviSbvzXSi2fYHTruUau0YDzh
            d9kvq1FC+Y3h8G0La2UY2xUirr/GaMjGh8UTeK1dwMPvS9XYvKwu889uKFgs44MA
            ORurYw6UXCecgrRyGDRQJtTz4/wCAMrkFG0hEvdy+43fg9DkjdLv26DSqBUVZnUS
            Mkb1B+5fReMqAT4ToTfAosJnG3vIrhHW3BcQ2aeJagLOB/nXGNHSs2wUp+WaPi+x
            TGQTETEJ2bQi+FkmpZ6OECfCWxgDbS/4IT5EmQPjI0xeyP1y8E/TjTVwEyCC08xt
            TRxMO8cOxwe6pXnJmcjBnQ4bZtQ2UwrDxf3VfnVLc3BSMfuT+D4Ya3Zb2eabUVW/
            9UzjuHxBOzsLemOV+r94d/MxmQZP5JjeJYnupY3fRwDKCazz2neBX7lc4uw13RdX
            bFB7lhWgOfXDaocvF0syz7w4JVE5CCokSTnRIodKvk7rkUNOsadx8i4vPXB51I69
            ujpaXbq32WhSIbnae8IWT5q27Hn0zNwZ9CPIgyuV/xule0cbryA4Rbe6GVTfJ7zE
            97DR3/rXNfuJWikoR0fxag5jZHZL/HuyZj+nAf9PHp2zc6GNLjmGTYjyMQBTENHU
            ZgEJAhC6haNcz/7beHSU0vbwE3U6n8n9oCa1nyfAkY4ynmoQnpDbqySOTqdRwlKO
            bUaQj1BevIs5qJuRTCKd86D/8srzu7XvU/yExDMhI7+vLzugdtSItaRNz35bFwmg
            awCH656uCw==
            =KI78
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
