apiVersion: v1
kind: Service
metadata:
  name: protonmail-bridge
  namespace: protonmail-bridge
spec:
  selector:
    app: protonmail-bridge
  ports:
    - protocol: TCP
      port: 25
      targetPort: 25
      nodePort: 30002
      name: smtp
    - protocol: TCP
      port: 143
      targetPort: 143
      nodePort: 30003
      name: imap
  type: NodePort
