apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: protonmail-bridge
  namespace: protonmail-bridge
spec:
  serviceName: "protonmail-bridge"
  replicas: 1
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: protonmail-bridge
  template:
    metadata:
      labels:
        app: protonmail-bridge
    spec:
      volumes: 
        - name: protonmail-bridge
          persistentVolumeClaim: 
            claimName: protonmail-bridge
      containers:
      - name: protonmail-bridge
        volumeMounts:
          - mountPath: "/root/"
            name: protonmail-bridge
        image: shenxn/protonmail-bridge:3.12.0-1
        ports:
        - containerPort: 25
        - containerPort: 143
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 143
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
