apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  releaseName: keda
  chart:
    spec:
      chart: keda
      version: 2.20.1
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: keda
  interval: 30m
  install:
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: keda-operator
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: keda-operator
              spec:
                template:
                  spec:
                    containers:
                      - name: keda-operator
                        resources:
                          limits:
                            cpu: null
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: keda-operator-metrics-apiserver
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: keda-operator-metrics-apiserver
              spec:
                template:
                  spec:
                    containers:
                      - name: keda-operator-metrics-apiserver
                        resources:
                          limits:
                            cpu: null
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: keda-admission-webhooks
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: keda-admission-webhooks
              spec:
                template:
                  spec:
                    containers:
                      - name: keda-admission-webhooks
                        resources:
                          limits:
                            cpu: null
  values:
    resources:
      operator:
        limits:
          memory: 1000Mi
        requests:
          cpu: 10m
          memory: 100Mi
      metricServer:
        limits:
          memory: 1000Mi
        requests:
          cpu: 10m
          memory: 100Mi
      webhooks:
        limits:
          memory: 1000Mi
        requests:
          cpu: 10m
          memory: 100Mi
