apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: proxitok
spec:
  releaseName: redis
  chart:
    spec:
      chart: redis
      version: 20.6.1
      sourceRef:
        kind: HelmRepository
        name: redis
        namespace: proxitok
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    auth:
      enabled: false
    master:
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 128Mi
    replica:
      replicaCount: 0
