apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actual
  namespace: actual
spec:
  releaseName: actual
  chart:
    spec:
      chart: actualbudget
      version: 1.1.8
      sourceRef:
        kind: HelmRepository
        name: actual
        namespace: actual
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    strategy:
      type: Recreate
    files:
      server: /data/server-files
      user: /data/user-files
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: actual.brennoflavio.com.br
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
      - secretName: actual-cert
        hosts:
          - actual.brennoflavio.com.br
      annotations:
        cert-manager.io/cluster-issuer: lets-encrypt
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: actualbudget-volume
    volumeMounts:
      - name: data
        mountPath: "/data"
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 128Mi
