apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - namespace.yaml
  - redis-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - repository.yaml
  - release.yaml
  - preview-secret.yaml
  - preview-cron.yaml
secretGenerator:
  - name: nextcloud-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
