---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nextcloud
  name: nextcloud
  namespace: nextcloud
  annotations:
    volume.kubernetes.io/selected-node: brenno-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
