---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: preview-generator
  namespace: nextcloud
spec:
  schedule: "*/10 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: preview-generator
          restartPolicy: Never
          containers:
          - name: preview-generator
            image: bitnami/kubectl
            command:
            - /bin/sh
            - -c
            - |
              kubectl exec $(kubectl get pods -l "app.kubernetes.io/name=nextcloud" -n nextcloud -o jsonpath='{.items[0].metadata.name}') -n nextcloud -- su -s /bin/sh www-data -c "php occ preview:pre-generate"
            resources:
                requests:
                    memory: 256Mi
                    cpu: 100m
                limits:
                    memory: 1Gi
                    cpu: 500m
