apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  releaseName: nextcloud
  chart:
    spec:
      chart: nextcloud
      version: 8.9.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
  interval: 30m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: nextcloud-values
