apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: libreddit
resources:
  - namespace.yaml
  - anubis-secret.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
