apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: libreddit
  namespace: libreddit
spec:
  releaseName: libreddit
  chart:
    spec:
      chart: "."
      sourceRef:
        kind: GitRepository
        name: libreddit
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    redlib:
      address: "0.0.0.0"
      settings:
        enableRSS: "on"
        fullURL: "libreddit.brennoflavio.com.br"
      userSettings:
        showNSFW: "on"
        blurNSFW: "on"
        useHLS: "on"
    replicaCount: 1
    image:
      repository: quay.io/redlib/redlib
      pullPolicy: IfNotPresent
      tag: "sha-d7ec07c"

    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: libreddit.brennoflavio.com.br
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
      - secretName: libreddit-cert
        hosts:
          - libreddit.brennoflavio.com.br
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        cert-manager.io/cluster-issuer: lets-encrypt
        external-dns.alpha.kubernetes.io/target: "brennoflavio.com.br"
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 128Mi
