---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: libreddit
  namespace: libreddit
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/dudeami0/redlib-chart
