---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.json: |
    {
      "platform": "github",
      "repositories": ["brennoflavio/brenno-ops"]
    }
