# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: renovate-token
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:HIpZKr4nxBtLsTC0twI6pOzqI/oOLwd5JSTTf2qey4ZAa8xZVzQYf8lGknZJ7acJq6bEbem6kr+mFF+X3b2vwvcrBXMznEP25QQ2ieYHWAzhgRp/j/tdn2rFxXRe,iv:LEO6t1ARB+ZjEZIrq5vborOcVbJLe6/4iePqBqy+qh8=,tag:Exa5s78erw2IoQrXvXkkGg==,type:str]
sops:
    lastmodified: "2026-07-20T16:51:09Z"
    mac: ENC[AES256_GCM,data:CsYK3Ea8oirVRq1SHnv7GcZ6HREQ5gKoHjiZKFXYLptAZ7+1lK39L5MHiPtoGg1JC9+vlNYVgDX4DEQNobQJHgqKsRBb6IPv/PM2Gn0HoBssyBmbztQhrs9IroXu1ZCGtSXMTX4U2ka2PJ7Ui2LaI3ok49FP7Bc863eOGs1fDr0=,iv:Atbmpvr7qHgxWBiuCoQgK3fzc6F208U1F0flhbQ+UPs=,tag:OnHRnkU7mcDJiDMCXpha2Q==,type:str]
    pgp:
        - created_at: "2026-07-20T03:54:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XAQ//Sel+3vHjySWu4Oofjyeq81ruKQI6yOGV24b48SzdfLUe
            B/z8Gm5b3RfMTIf6BSHst8Kp2A3Ag3IylucpxV23oh3LP/GTHaoJ7q2lffhERM/L
            zncw3xzrNd0dYU6+zRdHBRGM4P4mhjHfdCj/W3Ft0xJcJRF5cdCtN7ACUaoHC9RO
            s9NNnto878LXcuYfaAV1dvQP9vm2mpFQEUhdOvM0jipNxciRlp0LhyK0Rg08OLfp
            /g/ry1vb0WBUqWbBeB/phmmzgmrfLoG+UqNZtbd5EdttCCkknKgya0EV4JXrNRdq
            gmyTyThts1qLBcrTx10xbMF7FC4TlrJTRSP56ZdgTrbog02jTFizMD97tljJ/zyO
            MLN1jXWDGstckglcpcC6fIw5eXXc9P3MDDAFJj3hIugIOd8j2UzIO2gq0kBjGXaO
            OiX2sSDAlkh6HMtYN673vAAiPxGawx/L5yrJ5Qb4ChciMqKv6y9O93rIvsJSr+I/
            9R5KeANnqFwFMEjge3Ah2Q+DXi+S75elR1UbTyPQjanvljpla+Dy7tYlU2VUHQUZ
            qRM8Gcqwp1Moj8kaoPtNGskI2tDH5fS26qk9Ae5K4YLkIuzDnSc8TWvabmcUp9RB
            YTYF9zHLofaG95llpo8tUNtVf7qErLOFt+ZadGkFpsSC4eygRzSeNqqjFatYYHzU
            ZgEJAhCcyLQeKtZiHOa5Qw1qSkUAGRL+GDr5mR9dk2aaPN1Rq6BDdcrf9ArA0Cx6
            SKn4xeqlQH+PR7yl3UOflNKfACNk+k23fe+/aKAnozCTlIkbuachpyJSf0lURBg6
            Uw8MoFqlTw==
            =xNIc
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
