apiVersion: v1
kind: Secret
metadata:
    name: nitter-secrets
    namespace: nitter
stringData:
    nitter.conf: ENC[AES256_GCM,data:vJoxJY/tMFnR5uk/Ytm/HmqKOOa1B6c9X5fOJP+ZkzTyjXh7f+l+Uzgk0vEhLa6GIKcBQPQkEOslwzezRWtcnxbbAtZJpoEBtrLDIT9blK318IAAfV0c1IyuUVuPQDZXpr1HXP573ip7LlW5osGDcGTPSoqUfZxJ5lwfCktoJ5X+sAP+3ya46JQ3KOPyUtOWf0FfYzRxRweRRtZqVUDcJsxfGUUJFFfU14qziy8iK+++oSFsL2jgxU2yrroW4GJo/JInGx2/l1Z6VoULO6nk1SQkWNWtD8cRLIuMRk6nz2OO9bNUEBfxP4hnPQQDgJnwkFl7ZcWURHizGdL89zSDanWMA6jE5uSeOQGueIwpUxBRFQ5LwLSDT7lPD6FBBqEPz38OFmp+pA050Ru2vhazuZQ58Yfu9+riW1BNDQGGnZEQpwxm3a2wmj6V2rv2yA5NcdSxVUx9IjFOkXxJ6wtLAmEXdJiBQFRfF3EWrDboWjxdgS98cGAH96UQxmq6yLvRvCQ+dtn0e0iFIKA4MTuEDub2+GhJdfFQvs8hPKUQkBqPsschhoskIFHhSJOxxqaiFJWcn489wTpkzXBgv4kqJ2IuxX/VrNq2OMrjEeudriMLx8zwqY0N48SeO5WC7nJIC2O5EniBt6ojMSPeQ1A9IaHlVUtGREGsMrCzGyA383CyN0GJwfR7XHkvS7nwTzpZckGrJSFw4+j7K1P5x8T52dIT5nB8/AEbhlM8CvZw35c1fXCJHiSua/IC996iyN0k2ACLN7AywMQWOUevr7b4orqQlp0xdMlqdre3OkSOfMEMyomu1ZzHViwtguOEkdPo8TD5vERaJaqpn5hnQICGxC8rHW8WRBfw5aFxGBrVWuPyZ9U93/7dIhzXrxSZ/2F40Sh81fX2W6J4zbsh/wl80kZ2d8ezBt7VqFdQYFKE3RnUOkm31KwMjTTJzCJMqHb26yOyyDBZWMccRzF61pkN4v4RU+j8YSF8LrIwKPYKOQ==,iv:BW5R0EHLj116NR1PweNeAgQVntvnEzff2gYMIAue5qI=,tag:Oa55b20LFtZMNk0+ysRy7g==,type:str]
    sessions.jsonl: ENC[AES256_GCM,data:G00U+LQacoh9O9jHO3N8GcoaDDCVIir2EK8i6TxEFdoVxTxZc2+Anz6RG8RGxToG3rzzC9uVq173YUMo6IkcpMmd3xBj/bBhRx30ZsE58Wqauht4+1qMKHyDAAZhWPwS/3bxVPU5a2FZ9CQ0IwDCgMVcox0fQLfdbBMNlLymdjiff2stP3kpvIyLJl1EyX7bDSldzbjtUcVWAQC74zWWY/vBo925zsSqMmKuiki4eKQDdNOORAMfUYv7uMqVJ8Uhaq+Mdct8hKDRTgwAkPZf6dnxDYyBYGxINRFjdZXhF4dDCBdVS6kzYVSGFFZ0IzJgkE026rih/+rkbTBcPhaJSafUUz4g1BwY+BU4PfjsSFX0/XWuYy2g0tN/VLSVXGvwTU7Zhuc=,iv:FJ+tJHMDHZVZeF8M13k4n8zfRCVeC3Ez6qqo4q2ADFQ=,tag:v9Js0cX+E7zirqP3GtD8Ww==,type:str]
sops:
    lastmodified: "2026-08-24T19:45:09Z"
    mac: ENC[AES256_GCM,data:UX1bFznh79CZXX2bvZNMGWUth3SZ0TOwQklAn25UnFF00LF8QFVHivJhybzKxInwQdr+EATT5lIkVxURuSdWytfIrbhJh5j+AOPAOq1Rlk9gErVkat7jTkMUKkanR8Cy+X8oaYJjZiWHmDvM7poxcnE2vZZ8fTt99Y5LtP2+bX4=,iv:rDPDRUFKyB7MjMTOOYJz+nveX6/3Mu+A5DxVwy6bMUA=,tag:BXeRBHEsdGIxmDX3zV8HOg==,type:str]
    pgp:
        - created_at: "2026-08-24T19:45:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XARAAh4xi46NF0bTNmiZGGi3dka1NB142P3JAXgSJODN6K51c
            c5G5jtS1HoOpmNlj2vyTBiUfyReq9DwkCJ/+q8KS5XCPWNgWMF3S6jL4EpyH62YT
            +1m5PLVP+RamConJ+ii5eXmIUlQ+DZOpiv6y8BVOrE5JxjEXZA/w2x4/sUFpgBLT
            HVwwBsOhlHFyPqRSGcQi8dSZCgEhMup/A1SYGWFOppNh7G5+CF3565ter4USFqpf
            /N3FO73SnR8q6HdtbvSTbA6l/NL+ZHngu6X9d45CfhEkHeZkArbcTAwcDfK229qi
            +wckBKWn60SVpA4Tz4yDBSDVX1/cn1cVG08tljcL2YfglR+RJsPfm0DOks9HnkVI
            2dWsP/IynqlaMo9QUpwPCZCEBPgy8QoaXJ5yfcU+vnB2+8VwQ/J7rFXfCs27eZMy
            VG04W0dW1u4QXwu/Qw/Dmun7fGVperWeUkAgw4rzZj5VLpGmmHUDNm3WJ5PNqFbJ
            C3FruaYEhy9TPwgKhkXqs8e3H2IBTjK893py5c3Fj3g+NWm4MqJhDv3wQYh84XOF
            vj0QPDTVadJUy4IVCi52W/Ipano7uByyky9+0V8kARITaqRCKD4APTsQUGyt7b2s
            oWJjlWjrjTDZOZTX1bWIGdc2Inuoj5OrtzHDJD89/Gx5S5isvPFMrHw4atMN1KTU
            aAEJAhBLwoFeUGynazGLDwg4UahL1tb9m2jzP33nEMrWj2CJEeLnYgoYSnI+NVO/
            1xs05U5UbRtzDirqi9tnO6IyhOe6gdxhfd+Ho0L2DK+iZm9LLX2U2qaOZmiWBDrj
            MhCO90D0aoyH
            =/LKl
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
