apiVersion: v1
kind: Secret
metadata:
    name: forgejo-cache-secrets
    namespace: forgejo-cache
type: Opaque
stringData:
    cache-config.yaml: ENC[AES256_GCM,data:SAxx/QE2EDp1lFvSpAtBtV7aE7e/gXFbPthOP8zhDaA2r2DCaE0FovmdS2qtyHe8uZFwzRx4rV0jNl34eTZfKWUJ8Kz21yd6KSp2OtYm/kbsJh8LCzWN3RqO3MKJwdzYCV+oKpr2bYfzs8T1VLGK47eligZwWziMQRg22UayMycWAQXnkIdx7BN7wV02XPyPqOCtLkRwb9F6q35686/hmsWH3omIkyE55JrqGFlFxZeqngFoOvawMdXiW4WNeaDFZhCUTkgNLBmpUFFf7uJCykkbFdvo4hHWqSj3P0HJCWTCWfP8qsDANDHaL2MK6JQ=,iv:SAT0c05lEAK5W8eyzMeSEn3wCH6LcgPXdzWr/Emji+g=,tag:nNQfVkcvwAEhs/nxgdiWqg==,type:str]
sops:
    lastmodified: "2026-06-12T04:08:09Z"
    mac: ENC[AES256_GCM,data:IuHQcO+Vuc6AnWdDBLyNiGHA+18sgOsn4XuTUu645OsuBtwAiOsOnIW2PzEKzWb9s3s29/Y0jpcchfY9P65WrlI9O/AiW3AnMrJLrfDhOjM9Vu+JLC26Xm0RHtmsJxowix71/NVzherJEow7eaioUEQkn3+lAxw6YQl0QKD8IfU=,iv:FDN2M/2i24i0LQxB4r/Y48mhrEaHcH6Sj3m2sC5VhHw=,tag:UUSxyDRDxizIWx9do+z7nw==,type:str]
    pgp:
        - created_at: "2026-06-12T04:08:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XARAA2gEaTCb/Lo7HUEGEDbvnWICcZvRnqaySW/FSfH51htOb
            yu9QPTH5nQiWJbvMR3CZPXbW+q5IAFOoH1C9MVZ0dKQ2zX2Qd26IJOTNlKYf80kz
            bk5mXIH/wZJTjjsf/NhfAFUvE/qq/hVTByHlsMzQOwl0YiwcuORtPiOkgz6glEvp
            vKeAx+A1qBZHI/HigFcTjJtcFuuw0q6mUm0U8fG3mDz+YFP3Dhb4xiPd/SPa4rwl
            HyzcL0cMJAaMfnpnftr0D3u7uwNSdrwSO7E3QhMsYOMSIZELQhYUSFaUGv0ps/WP
            oW7f1BLtmNuQh4UyaYyHyD8UFx72d9b6CsTlkeSFNywWmcdqANeToThHS06LR7k1
            fLaNc5jx6KL7ez7UIpSEDyqYPk6Dm2F4uQCOs9vXMk2Ig7JW4i2Gj/4J1Sl+pJX2
            w1l4ajC5yX+NMy5ZYzhNhyC9FiPvaRYt3ug6ddjdExudydqPLy4RiQtFqaq7ns/s
            ZRoKyx4AarQL37foJD4ZWXeS6BVS0Glf2lthBi9UusfDi9hQp8eD2uMF73BnnJmy
            ejP6pgryrz0f64MAM2YO9DDGH4Xj18x3X86mTNvzVT769S0PYRAyuXlJO+MqN9AQ
            jQnrvjmBJvjYIUqy7+Xaea+ej54a4sucMeJU1xBGiin8/3Kqk+mKX4JUABhb5JrU
            ZgEJAhB9ih1kaGuIhx6zNe1AcgqD5enL9qJ3KcoeeVjwSc4PXax+/kdOTet9jnNZ
            RHPDIb22ukZqn1aIIOHku8+qqB59zvv/Ep5vH24P1iQXhN+Oq9Uk4PooF8U4MR1/
            /5nKg16CPA==
            =GeBu
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
