apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    controller:
      config:
        strict-validate-path-type: false
        annotations-risk-level: Critical
      ingressClassResource:
        default: true
      allowSnippetAnnotations: true
