apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-vad-models
  namespace: home-vad
  annotations:
    volume.kubernetes.io/selected-node: brenno-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
