apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: grafana
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:VhTZSRw=,iv:toZjpsy72bE0sjlPhREl3s/LC9TkAQHZUUoNGksN904=,tag:wldkRDw1N07xT65gTkpTHA==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:PD3tfJ2nfqc=,iv:J/VFm3Bab3Tk5GIyCW29gU1cZO5PeRlzbxUsynGCu/E=,tag:1bS5lYJHv+s8bJJ8wlX+SA==,type:str]
    GF_SECURITY_SECRET_KEY: ENC[AES256_GCM,data:WUP6AEeYCxbBFTeKZDvLO4c11DOCW6mCHh/fNz0nKwJPM+qFvbS+sbA1w6OLoOCtpWMi8o6zS93r1+5a8d7EUw==,iv:Pe/0QmmNP+YR9Fnt1Rod+5j04XGPpaFgB9R2nf2R1Pc=,tag:83CfkzZllLEOwapo3nNqvw==,type:str]
    GF_SECURITY_COOKIE_SECURE: ENC[AES256_GCM,data:xJjXyg==,iv:hs9BhbWkk3BjDa5HigbATXvokTTKUsDiAS755wFdFdg=,tag:LADVPF/9ZJ462iMDzurWag==,type:str]
    GF_SERVER_ROOT_URL: ENC[AES256_GCM,data:BL0afWcAJvmvpSmvhOXzmXTUnBXutyPgz2wyXnNgBfFrqM2bv2PQTg==,iv:uDJPwATLAldMANWUmCHtORV4Ujg62+pHUVsq0mWJHhk=,tag:cRq92soz+bXDk9K+eCGKrw==,type:str]
    GF_SMTP_ENABLED: ENC[AES256_GCM,data:S0Y5/w==,iv:5xuOPldCx+D1bFtZgCt76Hcj+HMxQu8arZALzar29iE=,tag:tfb5ldlXtBwlkRuPmOM3Rw==,type:str]
    GF_SMTP_HOST: ENC[AES256_GCM,data:1tbFcG2aFPYf+z1LL0WGsLJ3Vy9CGoQUQwWh+g==,iv:vPvrG8YRdbb/62wFifJzG0ifyO9ROmEykDziP9OAovU=,tag:oSMuQFJH0AOIkhUzjxhoqA==,type:str]
    GF_SMTP_USER: ENC[AES256_GCM,data:uqoI+DXwybO8ddD3sik0jwhIqJwojnH/tkAk,iv:IODrWbBUd+0q+D+7gnHPl97LD30J3FPet5K9IxXiCGI=,tag:8n2gtx1x0dBv5RWQ1jczJw==,type:str]
    GF_SMTP_PASSWORD: ENC[AES256_GCM,data:wvzE9uZKUuTk4DG0AiOme8AQWsaS5JVZ6T1v5qEJ73g=,iv:YKSjpvNdfWPqtkNGMGxjFrhav0GVwBjbnnpVT1l6Blo=,tag:H4cKq5aNxcBk+em0T5NT3w==,type:str]
    GF_SMTP_FROM_ADDRESS: ENC[AES256_GCM,data:WUEzDwYpqBRs7OHjmdm2NiBX04RQ/C/9jvYB,iv:G0+3sexZsP/opBHlRHm8t0+GVJfBOblmAVuw7gVh4hc=,tag:VvX8X2kT2KGIAOLRF1piIA==,type:str]
    GF_SMTP_FROM_NAME: ENC[AES256_GCM,data:NBLQUNGmFw==,iv:PZ4bbMl7Y8wGTve2GcU4tD6w+2I2t8Khp+nCoY3nyT8=,tag:0ICxu37YKwKvuBnj61OI7Q==,type:str]
    GF_SMTP_STARTTLS_POLICY: ENC[AES256_GCM,data:zP2H4/C8RokkgOhx58p4KKc=,iv:SP6TuCKPxDciejf1/0US+Ad4i43Vfp/iF/SPfIOojpo=,tag:Eslkp6Eo/vpTTsh7CGLfxA==,type:str]
    GF_SMTP_SKIP_VERIFY: ENC[AES256_GCM,data:TMY5/44=,iv:JsaQVzT29d9gKg9mWRI5TIa4Yed/zpeP85yl986bHJw=,tag:zAXMcLVJy0nmn4Dv0oJQzw==,type:str]
sops:
    lastmodified: "2026-09-19T02:26:38Z"
    mac: ENC[AES256_GCM,data:T1hwHALgeijBj7JkgJ23E4f5iRwPhnPYBoBpdeZEFQZg/bqvigYyXtHI3FxSl9rdq51Xie8JhQDtDrT9WibuwJHhcQ0jzcGZVUao+ymck18SnJX6B8SkESxxdYK53RlODnPZE64aWZwrWPhPVWhhJm9t8mr3c47VwD6tpHYpTWw=,iv:Lm1dbFOXXRtJweyOZLWQlzmvN9ZKKbHAQcIJkdCxSTU=,tag:qEoGRwBat/qebvldSXReuQ==,type:str]
    pgp:
        - created_at: "2026-09-19T01:48:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XARAAwoSwVHNhh39ywywLWO5yW4EnHEnNQDJnSozQeyFvSi/L
            yms2ZM2QULKYMjAJr3izwRWZjzNqBW7Ivr+VnZf2ynZhX02qIHXsOTKmbdHF3Uxt
            CNOWWz2qlm9nvLqyoLkrEGrcT/4t5kQVtrPwLoGzBtx6tLNW8V9DA41F34TgglGS
            vcGQYMkjXhRsVOLcTz6AaJl68/YUpv8/MlbshSy+xUKRZO7jeu5iFp408kpg+Ebw
            D6Ef8FSXXmZH4/qNccaekvlF/oWC0wcAnPilx/o62cvtHUXFIBOqvsSLp2u6ngEF
            f2/0PxJ9aN7pR+qzlJcuhZFBXe24MgNJDyVF6G0ot/2/jpcdaS/odagrsbsKe9I3
            fTjlsWrfKCLzZ1ULsFW3ujX3ju3F9i1bQg6yktHuRYScVQ8eAvqQhDY6BIXD53DG
            C9KvvXjA0dGZrqI9qb+hkkfkcOssQZCkLWTRV8ufuwCTK1qghbMfqGPPl++D3mtE
            Rg/OQByY3bHjRUa93NaBH0LbG3o2ANUg7DVc2CvmDYRntW6GDEs2aC3PWwo8pNLS
            fOHwSsebJc9USteGXNeijWoDOuraXxJfXhr4gGQd/fnzEwazxP66CYs14zM+CkM7
            t5fGe0TEdsApyTZyVLbv/+xCi9zqBARDCKE5laV1/WEo+Uvz0kOmOMZJu6g3jNHU
            aAEJAhBGuQUgwgnULj/YhGeWcrNKbDH0M/2cZT7+5auRhqob/FpmeVhZEnzDffvI
            oxxjnuM6kNkw+hdTUC9609uook2m8V9KQBAZkyh+s4tJdgE4+SnXvGiF6vcWsVsc
            d3CRC/R3Kotq
            =KVpW
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
