apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - namespace.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - pvc.yaml
  - repository.yaml
  - release.yaml
  - storage-template-secret.yaml
  - storage-template-cron.yaml
  - service.yaml
secretGenerator:
  - name: immich-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
