---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: immich
  name: immich
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
