---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: immich
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
