apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  releaseName: immich
  chart:
    spec:
      chart: immich
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
  interval: 30m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: immich-values
