apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirlingpdf
  namespace: stirlingpdf
spec:
  releaseName: stirlingpdf
  chart:
    spec:
      chart: "charts/stirling-pdf"
      sourceRef:
        kind: GitRepository
        name: stirlingpdf
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    envs:
    - name: ALLOW_GOOGLE_VISIBILITY
      value: "false"
    - name: APP_LOCALE
      value: "pt_BR"
    resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
    ingress:
      enabled: true
      pathType: "ImplementationSpecific"
      annotations:
        cert-manager.io/cluster-issuer: lets-encrypt
        external-dns.alpha.kubernetes.io/target: "brennoflavio.com.br"
      hosts:
        - name: pdf.brennoflavio.com.br
          path: /        
          tls: true
          tlsSecret: stirlingpdf-tls
