---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: stirlingpdf
  namespace: stirlingpdf
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/Stirling-Tools/Stirling-PDF-chart
