apiVersion: v1
kind: Secret
metadata:
    name: telegraf-influxdb
    namespace: telegraf
type: Opaque
stringData:
    INFLUX_TOKEN: ENC[AES256_GCM,data:TN0Ewe6B1hKqHE9RtPDC42gQLIfjK4F/L4/xfigYHgk=,iv:5V6cKZtZM/4SheAysQg5rxst80jc6fQt84rfEd5inaE=,tag:+8zfoiIkbdNUz8Lg5aG6gw==,type:str]
sops:
    lastmodified: "2026-09-09T14:45:48Z"
    mac: ENC[AES256_GCM,data:1wowiqUwPSdmeCL3M8WjCXilUoGbF2DLjhY84J7K4QIU6OFpsDRp5JD6IjW+Sqc2i37s0jw2nO1DoeYLB2oZAjHdKsnJlpoTao4MRqyN0Aa+VTOTSdvQD1L0e9Ud0uk7OmNr9WJXvCxDzNFZeZFftGq3f/0rmTl/fEwDLGXp2YI=,iv:Qhqb0TxtkHA274JHT28BZFjVDKhJe30GTTpvPVts1Oc=,tag:VtygWorMT3q+X/1XFHo0qA==,type:str]
    pgp:
        - created_at: "2026-09-09T14:45:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XARAAmsCIka0iJw2icViEPbh/4ZzwjObQk4K+hQlX8zOOoQDn
            DKRsKSoTSwMuMcLvQW9uIKxZwcKqVvBeLzC0qT6KGmzRL+eVf5/5YKQl6JduBR/K
            M+AN6tm6ZTxwnkW3EemV5nkCiWxP9U8abqHpaBQBMVg4vvzA5aKryQjilqIa4PHu
            +AolqjCJB8pMR+zMYMsb8USrXHdekgBHYufStwnructHG3oWknptznR1B3xu6+X1
            Js24d/y7V+q9jOoyhODFTfgVcH9xTmx4+6o3duUlJ68zTToIz44tbmaY1g0S3t2m
            nrBPidXrjdQNFRnViJFH2OMVIC86JZMa/1/5rpmlGqogzgeXkfMui3lDHb4xovVE
            Lz43Bq48LhARoUzkwNQ7I5scIl/PgRYG4vMe74e5wZUE7jLRyYz3VAp4Ohfz8L3T
            KPHAO+RimzM+ako5KhewQk0kEQ4VrfYNgZZCdzrnjfMFAOtRUyAHT+cVzLa06zPT
            hiBQO+gcDkjddZ0uVNSPV1gem3WdCOfBU82ERbI3fWXeCgtXicWK7h1yy+kmAL1N
            3W3RSZ7uT8zD761LdrfzcMngmqef84f8NtBd4ZbwJtFr/8UGXOYYQJ8c9L+nVc5x
            HnCvTNed+aj7XhT8q/c3057ySj0MbpJcciY7FydsVcwjHkuxkkII7unYFmIC/8PU
            ZgEJAhDshZLI9ioxGxtiREbkmEegOAQMK3wIOtoSjmDqwKs9A0qyt7DcXDGz7tjp
            l+FI9hSyz9HfKV0Gaq+evfLinDLueGw/r2GYK6OyYjh4kIlMBd75kY3TlVxfX+Kz
            YGVTqA9FYA==
            =syR9
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
