apiVersion: v1
kind: Service
metadata:
  name: immich-kiosk
  namespace: immich-kiosk
spec:
  selector:
    app: immich-kiosk
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort
