apiVersion: v1
kind: Secret
metadata:
    name: kittygram-secrets
    namespace: kittygram
type: Opaque
stringData:
    secret: ENC[AES256_GCM,data:gDSHbuXio0oErcst+34rqQTuR6gtvyboN+c4gs3ugLmU7O8uRcJL3JX/p1nwUslaeRi/zOnQ7SgxK9mxdH42+g==,iv:NduSxUDESytqEvAi6qHnivWdS3QHVTpe6RAVP3lEY9g=,tag:JInmEAW6g36Q1fFgHMXi8Q==,type:str]
sops:
    lastmodified: "2026-09-14T16:32:47Z"
    mac: ENC[AES256_GCM,data:g6nrQtwQX10U2D3749JJLDnsh+esu85uXeew7ULUdkW4oTZ9PVpWZBB/tc1v4Omil7ELweXVviDceEbOZonzsurCzE8el5BKIy6SS1xhsYwA8m3h3bbPtwEjOrUK+bU1+3TK4L9wYs+knbywSYgIDoysCXMgcEOeOm+ect9zRUE=,iv:HsPd1j1GdR6f9e42ydi1T/3o7soBh+aSOjQ8pjcwUTE=,tag:gdMuUj+H7vvTu0xp4K1Czg==,type:str]
    pgp:
        - created_at: "2026-09-14T16:32:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XAQ/+MAb+W/IgmjRQTnC8tPCVPW+lFfboxGWiwg22gYcgAtxx
            4770d6Hvy5g6kLxoT8jf48oVmTzvePKEHpiIDJFGzG3cZBg0MZLJZDZu9SJVGMHz
            H1YYJnC5MsREeh6je37xdCDDq+pl9IgD3A1gVD+Xz88Oz0OtS27axNfQBJ0YTtLt
            qhQAq7VD3y0WrrRrfqz1qHv02IbcFA8c3OiU9r07mtBsqcUV5Lb/AGq7mKwjYCgi
            RpCfjUwiG6orZFrEOJLxZgRPkVMKkYe3CMzzximEm6JefHaTF7GbHzMNtmm5xmgD
            MrGDVT0cFHoZNZCaF6v8tXQDGeEXTfnSQYsH945jDA7vdR9TnYRw0DrWeoAVTwn7
            t8nMlmR0nHYHmeFhN/ZEnCcHPbhquQJdwQIBV+G06WYA8jmBFsNUZzmZcRqaSldo
            nwTCQdXK/ueSi0id5ZaB8cQCWpAnGvcuzXVWdkE2Drg6b9HLrcf8p24mgQJlob7D
            zMyrQV0aKhXZ5CRCBQ2xhpdS/AKBzMA6gj5/HY3g/Wo+dupc7IMYFq0+L40bqdcH
            sdUGwCTa30XSNFP9gbQyQG8ByQlyWTLrhj2tEW7kyde6hJFB8Ct18ffx2Hf6lTLs
            V4gXimKqEvkBE0Q8VEhV8EibBvFzhmRdpmjVls5uo4udIU+dXcQrTYUZs83WyprU
            aAEJAhBw+FXM3ZSgbBWR2ZRgnaDSXDnBLhQCjj5xJ29p/YBPhnahv7WfeYJLvqBq
            09e38QI78uOx89mhbNFdH24H+kY1bI3F2CFgHTsThJvhk2w4bBKKW41deEHsTJfo
            bJedqIrBIwN3
            =jErW
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
