apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roundcube-db
  namespace: mail
  annotations:
    volume.kubernetes.io/selected-node: brenno-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
