apiVersion: v1
kind: Secret
metadata:
    name: internal-external-dns-pihole
    namespace: internal-external-dns
stringData:
    pihole_password: ENC[AES256_GCM,data:zkqUVbr8uM4=,iv:Wy48nRYrCpCYYFod2OPaJRcaTDnoCybw65zga4UIuXI=,tag:UsDQGzX4DXQejjx5oWpuJg==,type:str]
sops:
    lastmodified: "2026-08-03T22:03:02Z"
    mac: ENC[AES256_GCM,data:RiZIvNocqc8wFpRiWEAS1+R5Pjx3pS4Euy2AmsibW4aa4EByxoyWR/j2I+ExYDAw9sbHroadvU6EOj42gN9jutPkaG7T2TeTGMM5V0gfCODarnUS6W6rVr68gQxUNM5mc9THKb6vk2v5HhCQYVvFsZ9iOAGgrBUzTjLm8o0qnxw=,iv:Aoc0oK0hcTrGQi9EHMs7uMZdMEOgWks/gRFqdboe48g=,tag:Dh7GoEsIHnx/PK2gbAdAzw==,type:str]
    pgp:
        - created_at: "2026-08-03T22:03:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XARAAk/yYHealB28uzmGyRqIDcHrNUO3mR4ge8lSx4Tsm6wZ/
            xjJTO02C2q7mSZ4j8vHXg+M/Lf3ZZ3Uu1euiF3iyK0S+jADblZR2GrMxguXM9iCe
            vVrMag/8E45nEoZpYAJjUZ/ASkhwGN0nrMuUSE7mOANfCuw2BGzXLB0WmgVV3CqV
            e5CN2TDVh4nbOcKxwZRms9ovfehvzF4iZobas/0Q8hWw/FHg2dVep7BjrhKNanJB
            +c0yxs6B2kvC96mAVJQGTiJplUXJZuaXlSn4tlHfZtvQusVTHTY2VIHB8EUQiyxi
            ro+OeDc6lp9uFbyBFxwazN8C6vaAyUEvmkqdgFLIUuKPTtwg4Kf4iWIJlYYrLAs1
            N80WATKH1kvWTq0ySjHr88CeMdPcdVkXRiq2u1+dDBGsXJknRlGDBdBRmEw9jWUr
            Ph3Phxm13BlBmU0ObK+U7nPveC4SNqi+ZZy9iQKmLUsUQ95VXnIBdKcM3M2QK3Yr
            /BGrII/Rc8mPz+P2o5uFPNv0KpirNpsWGlyk6unIDkHko/GCGZKEa/w6E9X7Ile3
            9zB9tlP0tQqzSmSTy8Z/vliqim8gbRm9pcoMooTS+38923LXgDBl9K46rlGbA+LT
            XW09VkHl2eI9P0LX6H2Ab0UTkRG3mAs7pdAJlMpfR21MZk2ePASn1ybJcVJSFsfU
            ZgEJAhCGU0CFuqVTEbnu/7zP/JFbZDLK/lEu6wrWj5VV8HjiHFq0UKBp8h9CEMYD
            PwjVoE0KhtbAaHct+12yJ+vhUfto1U0XitRtNOIix4GQ8Qq3q+D9hGYwuKixthJ5
            e7T215mGhA==
            =Md75
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
