apiVersion: v1
kind: Secret
metadata:
    name: route53-dns01-credentials
    namespace: cert-manager
stringData:
    access-key-id: ENC[AES256_GCM,data:R6VObjvGdVdFM9X43luHCpnLBis=,iv:o25F3hiVRTzc1+FKcED/wT+MXm/RQuUfFj46gon0Clg=,tag:iUCUVItKBGRoJGRcw6PWCw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:OSw697xCRbfvaGcXToFlEao5LLnNTbLveNqO0MNDui+k5Ah7GOFKXA==,iv:zTbJWF/z5mHc5Z4NhovWj0cFcd8OEJE3F1XbsCGEaaA=,tag:1B4CYJoTE6fWpW9tp1dyXg==,type:str]
sops:
    lastmodified: "2026-08-03T22:20:52Z"
    mac: ENC[AES256_GCM,data:9jfNs6UfsM9wEei/n5+aa5jMtmpmd4xDJotgje5f+8tBFy0WZ6LwmI9vQnNjGRxBQpFq9yynU1ZdEuakpQKK5mXsbbzR+t5xHbAPkLS0ZCqk77VieA/gRUD9G4SDOo/T33UwmwPKC8j/H277Aqk1fbsSEdxc809L/2hLS/BPEN8=,iv:Thbadd7RrGqmJeIUs0Bivx0sJkHYUDc2a9Ib8dhrIs8=,tag:koX4XeCbf/eXuUoTH1Lqbw==,type:str]
    pgp:
        - created_at: "2026-08-03T22:20:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XARAAp1l/gKm1qBLLiTwqPS7PCnOHoif9tlbWlfhGuluVOVS4
            TbYecOILOpAQI0Thc5T1jp0um1kADiKViaBK+8fDV31ZNxKa/8pxL80zhDVvEBuk
            0IYhd9pZTjxrW+LLSmIkmDfZJNcevf1GFnmiFCeg2O+GMol++f7SVuNhQ+66o1QW
            Nkn/y4VlaK/Q4wiqXp5rw3WfzB+zAdNsfT16nMgDRngeFA5KIclo2IXVWUkbTN9g
            5iV5R0tw0tSxxILsTa/0LNx2aa/YSVAxHU/X4+Duh4AQutIbf/hX3dmaP23UL5hO
            GhlSB7pv8GlnClFgJfjcu2bXH1pT3tb4pJgBVrGvM1gvhbxGUp2iEiwuyn91840x
            WpYYL4RkRZYrPvhRGGPHL/CCx6XI/YWNamxtR2koTFH0CNqgl6CgPJC0ziRzAMff
            WX/Id7DOlCSTv/CHFXcXYaUcf0dmNLyRJKX0oRoRRyyHHVntv4rxqCfU1zPEHyvO
            Jmh3YOLMY6SQZwE0p/3GNgiSJRYpCZ3HETLQ92x/la6VEiYWeIobeah4vnCG+Kit
            OUhdW3HdDBf2ZsQvC7hUM0PJJh8jTIbIyvPogh8OBxnG0w38pgF8/0ijItDfxAKV
            RZ6evUT3MarNChy2I4xkv5pBBqYgY06QRn9XlgtGY5baWuKdVrbFpFDdtR0K7gDU
            aAEJAhCLI/mZaO4xS4jjaJzo5B8ZjzhwE+BGrFjK3HEz6CkrsysEpHclAf+OhVVy
            b2nAvfLEipcH6nNE4brUmveuPrOkuExhmOLMMGYc9pCKrpRYui/PZ6Y/PzHf5BD1
            61xXAPK+8TCR
            =xTQ1
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
