apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: coding-agent-browser
  namespace: coding-agent-browser
spec:
  image: git.brennoflavio.com.br/brennoflavio/coding-agent-browser
  interval: 5m
