apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  releaseName: jellyfin
  chart:
    spec:
      chart: jellyfin
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: jellyfin
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    jellyfin:
      env:
        - name: DOTNET_USE_POLLING_FILE_WATCHER
          value: "1"
    service:
      type: ClusterIP
    ingress:
      enabled: true
      className: internal-nginx
      annotations:
        cert-manager.io/cluster-issuer: lets-encrypt-dns01
      hosts:
        - host: jellyfin.home.brennoflavio.com.br
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jellyfin-tls
          hosts:
            - jellyfin.home.brennoflavio.com.br
    persistence:
      config:
        size: 5Gi
        annotations:
          volume.kubernetes.io/selected-node: brenno-server
      media:
        size: 100Gi
        annotations:
          volume.kubernetes.io/selected-node: brenno-server
