---
apiVersion: v1
kind: Service
metadata:
    name: backup
    namespace: backup
    annotations:
        metallb.io/loadBalancerIPs: 192.168.20.11
spec:
    type: LoadBalancer
    allocateLoadBalancerNodePorts: false
    selector:
        app: backup
    ports:
        - name: smb
          protocol: TCP
          port: 445
          targetPort: 445
