apiVersion: v1
kind: Service
metadata:
  name: backup
  namespace: backup
spec:
  selector:
    app: backup
  ports:
    - protocol: TCP
      port: 445
      targetPort: 445
      nodePort: 30000
  type: NodePort
