apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: lobsters-bisque
  namespace: lobsters-bisque
spec:
  image: git.brennoflavio.com.br/brennoflavio/lobsters-bisque
  interval: 5m
