apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wger
  namespace: wger
spec:
  releaseName: wger
  chart:
    spec:
      chart: wger
      version: 0.2.4
      sourceRef:
        kind: HelmRepository
        name: wger
        namespace: wger
  interval: 30m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: wger-values
