apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secrets
    namespace: forgejo-runner
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:5IKZnN2jfutfXnjkYeMQNulOriqAVs1Ko0AklO/sC+gaEaPGOVQFcw==,iv:UHEYkrF27QDUHS6hsmi73CMquhz+gVNvG/gVqDw3LX8=,tag:dUd/Y0WYsuMJysi0s9sj4g==,type:str]
    runner-config.yaml: ENC[AES256_GCM,data:uPkrZd9tEidG+gXmrd/TJjO0HvykFeFHvBJo16+J9McnA0u9ryHmRHDk3vkoR3eizMoJbZZC1FQK0Yy0ziLHrc2rGH4yi3UJ1Q1TA3oRRuYEOgjTbLURz2U3NWoJL+taXMLlAzEPopSrPsE6NT8ksaPisgwqh73Ky1M+iFUa/Mb5fwHTh35TgXqUklL5afgZQHnBGqDAsw388my11lgdKqzZWLR0zLCiLb5xmfpI0bgMFONGCUFKlSGBrDeAv7aIe9HWfPv9JNhRllBQHHg0fSo+npPGqIuhyDMpCzs1CwC5vMHoMD9LP+PcY+LKIGltC/bfqWNfP1Dr+L8ys3B/753dAVuK039WgU8863YI9AYXE5Gzlb7esJ1OBKhgnZmVEtVqBec3Nu+Lkse1Owx9+XIKRogaVxIebgeSwTu+6dWL4Bmdo99tUNh9qvK0Lsa3r05nymStJmEpC3cgG3lStBFiAaAb9xGqHDYNBFa/hjL+TCx6oOMDrZuj9VtBCYvRhrO3D7BPcjxZGq4kaDX2LPi69y1J7OT1BrrApWCO3Zsd3NWf2KLfWlafayL/AOI+kxEpg9g+viwwig9RM0k71NibDEtxufqvL64hY/tGrWgrqvntLaU+JLjfJWX7SAhVHX1PBLRsoR/MKNcEBHHJ0/9+ma5F68Qprffbco22v3H1MNIlwoY9X7ozoI39lJ1nRpIOKjb+qSTUvhbgqSzwmGmC8lr+2x4BWB/Uml1GiAJixOCblNvIEVDZeCuAANLtVUT26EEoKmtuiYweopOS3yPXYAcwzDRkJzhqx/SxH+4IrM+MiheVZ6TlFJWniltgQccTo8bFfmwkUMcbautg9YX0mAx53H/fEJ2c1GI52xKZLqxT67OTg/gRvuHT4AaCwjDUsl7b4E7ecL3qyXcPzOOk+r2oR8WS25nftuCL3UpUw8nEF+7cdvK6zMCXy/b9sdY4D7Mf2kL7NX7T4CfrMQQu8I7uXktxjl/hLCM3bE7nip/NmISNLmcWvzCtagTLzD5HFFcG79pwQGtz2ePS5G2PxFgwGtfH6rc=,iv:Dv6PASKkYp1b0YVbAgoT4WQzNbA3pqcvZwuiGsS2UFA=,tag:WaU1f6lCiNLItgC7NgxmAQ==,type:str]
sops:
    lastmodified: "2026-06-12T03:29:33Z"
    mac: ENC[AES256_GCM,data:k/EQrQwwaUcLvs76+I5BOmhcSWf5lFpwtNOdfkUn7tM3Pwr8Fwso2j/SySGBzD3KMzQDpM9//rKj1POypJ8jzXAuF93mGbHQvYCazdFnwWPZg3fAOzgOepOmrszj1ehhR8VYooXliUIs8MpTyeU+zywyQdQTlZYWPYW+Y5nId04=,iv:J+RJeGKRc5/VGf9BmmGiocD20G0q8PWM/S3vSRTAhAo=,tag:5QW51L47grNmKpu1X3I6ZQ==,type:str]
    pgp:
        - created_at: "2026-06-12T03:29:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XAQ/+IX0rBw7lQKWqE6SNVVipTp7mYsYZaTNiTYE7BzwpUHMN
            686mtr7aT7HVPOBM+cbmMCLUFKNhw2QIpyicKzNbdiFuMIuFbEG9c1yAwa14cd/h
            jRQOpI5m42sYEAvojjCT4UU9ntRr76awvCT4TgaHdhJRryDI7QRrF69wgJoQweFG
            Bi7xnC/S1JyvJFd/Q/apQXyVdFC1jI+Q1BiZwV31vdDgabj9icXjYA7GCJb/pbzu
            232g8hnQz8NudqIwADT6HTm9Epi0mZlai6K9huVsRghF2AFiaTcQLT2BimhOPQXF
            cqbCLOjVoExcglPZJYszexEbnQGBbogJ7keOAbzeSUDcw8T88J/Levb3QgRcqc90
            MwqYgic/6fPNvbTgX5Abgqn7Kdelm0ZzME5AgEz3n2D5+YaifDj+ngDvltVGNxo+
            7LO+8ncWyQOy6zR7OLehqcGPMOvVTNlvKcUiaHLkjh9nJJoHoOpPkOZRcoZzJlej
            cmEoeFimEgfT6UTzRSvPAdQie877Qh/G173mP3pqDaXZKptuXgg8GY3y7/UpUiKn
            fQzGYLJy95pgS1riy8tQO46MFT1/EwfPQODgOwnpQaNlP1rY0fjGedNd/vbs15sa
            i5tfgi23KR95+He42sIX6ZoI75bXKLLtwWLm6ddm9jEbqD8FmFbj1rtHLXQkGyPU
            aAEJAhA+lBIz2wOBXqW4Gwgn9Aj846BUE7yLbLPE1fCFEhLOQny36wqUdSqIrXBJ
            KQN2Yr/XTKvQ/l23gLQNOleIDBE5H6MS1LwMf7KCBYPc7ljzUQecXepZl1DdTXVx
            bMjFaPCnoldO
            =ldni
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
