apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secrets
    namespace: forgejo-runner
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:64e2MNypMZLYs1SSLA2gUTgq3ZjG+ji8hsJXB0Il4s34HpV1lvRQKw==,iv:/eUsXozXw3Ur9nJ4DOCjx3dvm8t6qr+M2XvWDmzwJHE=,tag:fJ2NOPKn77Q/MLK305qrjQ==,type:str]
    runner-config.yaml: ENC[AES256_GCM,data:7Hzccc0aQJmV04ThZu6IkTYh8WRCovVI6Rbjx7Ty8dNhKm+gJU4tvBeJXHuE4MbsMSVmtIdc4fhvT0XS7T8eqT/aJPPoHCjUEdntSea41U0UDPJUlItny9LsCufC383PqhZBhdeAYKpEWlukiPda5ION9929AW9SZ6CDYogL8JH3Fr16K8kpofcXkmgxcbkUOdLmfqNBzkMcdHX+eOXZVnePDWdw1wgadD0jEibjW6K2xDforcXFB0OIgp2VUm86vX5tzM3WKvSaw1cd1onlpPm7e+RX8z8W3pWLLZoXrE2zfWNTzQOHrnWHwNCdTIfuVycnwcqVfaSEW5hnEviTJE8YV0H0gl1TJqcrkYv/VEvXIiisCQJV8pfv3uIgd5awXjeHSNxdmIN/uZGHBmFnvnYaT2TdM1T6ux/HrpdP2X7297/YwYpz2vhFmAiXeKGLnkCchHu9m/2/dl3w+k+R+rxm7bnatWbTAZEFr1rD7ZV9sYoexOBDzo9f0zPzWSVCyU4j06AHQUAvgeJ5dYw1sj6kb3bj1eDwUzhS9CopsELtAqKy0laKqHD8JRzr00NxAl7EljoGSJa7n7nXNYXUydGVLy0HPaDiCKr0WCwyleC45laK2GVLWvMRkQbLhh3srsBiqXtkkkHtv5doQrm8JJZ06e2td9WrQkV5vKca0iEGuYs+gqp0RKmgjjpXrM+Ylnt7cSofZY3pggW2mLyBpLCFrrANDJn1KP0kIyMW5qaa/cw22zaEGPCTL0lUR4CRbnQKZQzHHbPk3jm0HqCkmmM0z9igfyckBs3JnU8w4YdRoJlI9joWmRk8zd/SRc6+C4vAbz5Cg5z4eVT5C8YZ533XfSPayIhM/ctIdoyzIDhGb9Bd7wYg+s6ZkRknstwgpmRHOPjnbNbbyK39IXPj1Q/UlL2ZQ5PjDocs+tI7ORWBabVZg0hSfmFgOEEGh2SCeF0OzvHK2IC76fMwmwwOAgqf80X5uRVod7KDO2n/MjLf6Uv+avGu0tGgLqL4ixWhTZbpcgYaHJQ4gNOxUH/VV2UEoP5va0trREGIt7HduddIhuc2Kf2/YHi9+2hfAZCCn/IgNXbhAComFr2f0ZXELHWqTevP64C8Gplrxi6dNyzg521Cw5XDQ0jW+XAjRHDmPerBatYuE87NMuGXu3p3CnKoBLN1fxN4m+dKPy6niewEn7LXV93UGlFqiXgfS9vJEXIAeUZ5kSP2QrIiWpEjEa05jODFObVhFAdZ9GxvKyPJzyB1Sc6+6DNAJnhhWwCFrOlHG2yDuZ+l17kGQMMsZGI7tT4R3BHSonlXfjQlPKoFhHjmMgNnqttmbSB/cGK2l2FN/CkCP1lxIpGtxsRHVZnfil2N9uigF7ZDmXuEl7D6lFcYfXsXsaZh/QU8J+D7n7//diNTapRr+fcZycbHivVcUBFQ6Myhuc6YTLTFzS9u7P8+2m9XSry7iqEkCdsBIAA+C2yUDybNHkbm7dU1qgu+cnYGz6ncYthvWuMd4jCRgJtNlug+gd4WXUfmYSAjVPOdonA5WJxPZnL62E0FQTHCzOJmWBhbITBaM0Sk79aVDm87MOsX94+2Oc2oiat/PXM337mfOdzQs1tXj5tZ017oRAr66wcS7PajRy2K3nTM6ayfsxNt6N/ulYV54emnJDETX7oeOT4TSVcap0zk+aUO+vN+eUkDvG/TZn0DtV0HkaE6YDy/VjKx05lP5hTrFOBnyCdpSb9rCrGmJ2VjNCNs0own4n8Mj2yOOFBEjzSO6pOF6XN/LPtfIZwXch1KN1A+tKcfFel//EZPDaIMzl4SDJ0lZhl+PJkC+nS5TftvSrJu10fVUB4demmeqgXxECP/2Q==,iv:oxDYi1//0JFgnxCh6p+RO5mnwezBgUaWlJxiY+hVDF0=,tag:DZds02/kZMeMiTdG3NGURw==,type:str]
sops:
    lastmodified: "2026-08-14T00:07:27Z"
    mac: ENC[AES256_GCM,data:MToEpTvZ5YtsLwhNClmAI7G+PMo/tBIko4BC8AfFms6b8wqJ7QXP6YPyviftFHcDeyvJfsP/dlhbNsR3nrwzyIq92JwbQmmcSSKU8ju9gzR2Eh4pb4J29weJeNuQ81AD7taTJxYLmGYUFzqKkJNqFkBqHHXLRv77Q+E53Zih0UA=,iv:D81ga3zTMEVr9Ei4zNUcVY7NJE6a31PdhqQ7+sjYjQU=,tag:5UonkbvLZkX4RYHOXUY93Q==,type:str]
    pgp:
        - created_at: "2026-06-12T04:08:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XAQ//RY9SMLIh8zBJcSv36mvHICdl5pp3rK4HmLXwpwb971MQ
            cHauMBeYrp8Rnu6xjhgzQYPIPPPfTRAJYO507FTn3y+v2SvUnKVTnO7YJoC5Wlu6
            wPIBpxS/EAtwbBrLX97vjhAb47v/Cq1flewT4mvivrjD+kZ5IFMN8QxQEdrAjARS
            00IlVrzBhP046kucn0zhmdkcyp1OyIPUHAP4NiJWxy2wqnE6op8EqCusoK0berYv
            YjWqopWL7wFiB06TmlrxSN3Re9EjWvtkbPgraeLGlDjETj/JitMFx17s71Va1qIp
            w2kssHOLouJ6IwPIvJkN7Vd/CtuzbapdgeZulMXhHmgID2NPywUsvA4Ke+OR93D9
            bMZYkqemLYobn1He9OjYfgzf33cxAPAtvQnQKLgbKDVomfLn41JVW/Epihka/Q68
            PNZmokNcdC1dn3jeYDixuH9Bygnf2gYId7/0L76AdOCBerJMmDkAP/5uEhOTXPRg
            dOWVrRp1kNztT7p2+gY3RDQME02zU9rQk0SKAU9Thu3CDdmSvDjGnBSsWnBLO7WN
            pVcv/OlZTEyeB3QWkFzprFnAo9IYdqbvA22OHtad4pqEeRlFagQzDoUXrv74DkDJ
            UN1pJ/yrnUJvOh33gst7FR0gksLIWb48R4jJsTMKvohD3SO6vJLg7RxCSiJ4DmrU
            aAEJAhD+nZ9AcvXMZEkq1cAHQl02YqvDnORvvS+jrbB6X3KJi67pDx8mSNixWXCH
            z6X3h0/OCYkxX5pUIFWzfn/LiC6eUPiuvjw2a9LRhO5bP0YWYJS110ipjVyF/73n
            e12XYXXH0N/6
            =KD9e
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
