apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secrets
    namespace: forgejo-runner
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:64e2MNypMZLYs1SSLA2gUTgq3ZjG+ji8hsJXB0Il4s34HpV1lvRQKw==,iv:/eUsXozXw3Ur9nJ4DOCjx3dvm8t6qr+M2XvWDmzwJHE=,tag:fJ2NOPKn77Q/MLK305qrjQ==,type:str]
    runner-config.yaml: ENC[AES256_GCM,data:5cz6VkRKR6MR76wx7+SHc9suWsgTpGIpC91ZsZo8sxaQSdtW9NyuF9CaeWK1lkxlKUZm4FTQ6ted1Z2HhTeIuAgXfMC4Yq4lLqWtluS4tP4ruMedW7ZRVqtZcfwt/SMH4jlrPZsVadcU/jkSdJVmuWn7oeDFOESGuL1VjR0dOU3eTIFT3ObQgoqyYXwRYe/jFrpb31rA6WCtnhvK/YQ4nIxcDj/s4h9drzuWwXCj/aPrJDA9TAlCmSLVG9oLHC9CuI2crmY1+ZQhYdfme9YxtPbruScHyiJcUhzBXD6LxRPj/Xbci5yuW8L1a0b9k9Rv7zoTy4xbBJDxo6rEyuY6ltaUiBsWRNNwOcvix9DDq4s4T/RRJxzg3nGvz93WnwEy3LrQm8GsxtaNFUxX1ob2J2u25ML+uH5LbxhU1JUUfPzX2KdWtsnpXBnWAeMCP6G0Uow0+HsiAPKXsB2HBjedTH9ESlHjXQ80KU5scRVXI1v+0/Ia2Kw8kHFsFx46bhSTjx4wORSp8BYoKuBgH7lrHDsu1gAi24zFxA/kveD+BTsKka5Jk+6pYvdYbH8pP3/7/D6d2Sz0DNlZfcRrqXRt9GSAt7sQlXZggeEQOthKwUJDqB+jnfYoG1SBdSTgUfYNg5GMcfJucsg3v/z8rv0lN3nBrC8kir8ntctCWXRSau22Y3kTDV0/TEEwPIkbzx40bbNAcGCivLWCg4xOpCcUe5aBbLhVtMPcEosE7SPtjoPoDn4ph9WFEMhVI1gD9A7v2uz5ym/UJ5DPqxm1Rscl8pBnFL2Sz0piMNA9Z99dlbiu9bTouNmFpTt740jsMUwcbJ8gkDR16cS5tY2duJDN5F/jnNVKkmrHv9tcRMbT+L7WWwcak6A/w8T118DxpG7eNzV0va08yoSbYjAOU/2D/UVfncoJUrGrhSTEq2ktCQDtKwQlAgZwt0ZzcQB1ofX1DFSVElPQwfwLUVcY+H5jEb6SlZUHxscswLVBMj3VUI/6LtZZVJOEjAzQrm7hhsMQGB45HAHRog+0xSEV5PJ+zaVTOiDjL8nFVGvo/mDRjd4wjcMqmkk7DA7ZmTXO63qY4geXaz+mBqyab8e9ZO8RS6JpDT89VtJkg3LqURuJnP/vPc0uuV4iOENtAjA+iWcDamOqW7EGq74GRnz9vwXfcVPUyJpedQIYbCJLme/dHOlV43JQfGGD3YVu/nHfEVTg4+fWJqY9EeZSKydrgfuJHlb+gbGIo9/2p5eEheRmDICwSVnu5qF9mbKHXeIXTuMaawt3yAnuIIt3dSeFGsWIB6SsXugi3ju+MfggnB4UJUDxW9kURV8LXEiWWLSID0yaR806b8dPUW0geeJabv/sVqZRcEWhgURr+9o8X3jPEu8lpjao+8uzzMJMXMaYnJUkV3HM08hbBczRJo6n+mhWpAK1stc7/Ksxk1HlQ6jubjN8k6MEP6nfCKRrFgRO/OlMMNnXKAB+2Oa2vkjH1y6PsXa8nN0nXJ55rLPmtTYwdwZvijjSfMaSBMhETCdN3pwdpxoyVEWrXeSi91CNlOpguzEJUj1mgJfFm6Ko33NTJvIoPAVVLnndf1P8tm7gcrEtIkdZRo83Uh1EfNRb/iyZOlKdBIG3kOB0fHDvCA3dCzD1zFs+xWLivgo6lvo0Ce0NLYhL6tFFHSxFojhyDjCFF7VGTECNJjPjyQi6d8k3KXejo1502TL4SEOpCBwh1Ldaq94VstAg8ZWzSPx/I09lxMNylKhbGt1MTlEl1hD9wqiAqyzLl9M14E6uUCtskMqPobUOMsT+bd1czVIFKxnmP5s+BfQBsU0Rc8jcYbSxYTn23gjf5p3/0RpKKOK1l6Zl5efjw22TSq09eUGqCsiKzGqHEPxlcVJVY7j/BupbkKaFPBpTSu8dOOJXDlM2KBLI/VvyQHvEbVenQ+F1He2Jmm9Ic4X0zHdFLwuDbtJhxOmWIGzmLK5ri+bpvHR0TNr1S2k/QDwb/pCKg2Godi/7kc+HSHR19oM7gGgjuAoAQOPqDbV2VWvAIgtFR/N9lcdB5BDkdsC6uvtJSIYz/4Gy5M4RwwOY2rVXdHak0ywctR1TrndHya+IFljOi9WLd9TPlQ/CdQdG9lT3rW439cqvmE4InH7Ykc1EosDR9kGCjRPgu/JjsezH2s0ozI1K9wmxqvi+YQ2kABuWQnrhilyl7JOdpX4=,iv:C70lR6md0G6BHQTf8XGzCIMXABDYTo4odezJU7ccKjM=,tag:lC7St3mIEyH4DRQEYAkPtg==,type:str]
sops:
    lastmodified: "2026-09-18T19:46:42Z"
    mac: ENC[AES256_GCM,data:wqkSkCayUVK+BdWviCbWr60ozXODVcVA0gvw+9YhVjjWtuaQcFKheFvGaVUFv6KDP5HBB9s1rqOpzLpPO4Mkyzm4rzGUuGXzAtrH+VhHhLTOZHhJhkloiGD11wQ+tUIk1/GSP3kzsZlM+6FkTSG0h1CnB0jm+iPKiPFGGymJjV8=,iv:rG95UELybf+wDBSF0PE3fYEaQE6zJMMilYoHv0iWT7c=,tag:F90eW8ouf6d3lhneKo0stg==,type:str]
    pgp:
        - created_at: "2026-06-12T04:08:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XAQ//RY9SMLIh8zBJcSv36mvHICdl5pp3rK4HmLXwpwb971MQ
            cHauMBeYrp8Rnu6xjhgzQYPIPPPfTRAJYO507FTn3y+v2SvUnKVTnO7YJoC5Wlu6
            wPIBpxS/EAtwbBrLX97vjhAb47v/Cq1flewT4mvivrjD+kZ5IFMN8QxQEdrAjARS
            00IlVrzBhP046kucn0zhmdkcyp1OyIPUHAP4NiJWxy2wqnE6op8EqCusoK0berYv
            YjWqopWL7wFiB06TmlrxSN3Re9EjWvtkbPgraeLGlDjETj/JitMFx17s71Va1qIp
            w2kssHOLouJ6IwPIvJkN7Vd/CtuzbapdgeZulMXhHmgID2NPywUsvA4Ke+OR93D9
            bMZYkqemLYobn1He9OjYfgzf33cxAPAtvQnQKLgbKDVomfLn41JVW/Epihka/Q68
            PNZmokNcdC1dn3jeYDixuH9Bygnf2gYId7/0L76AdOCBerJMmDkAP/5uEhOTXPRg
            dOWVrRp1kNztT7p2+gY3RDQME02zU9rQk0SKAU9Thu3CDdmSvDjGnBSsWnBLO7WN
            pVcv/OlZTEyeB3QWkFzprFnAo9IYdqbvA22OHtad4pqEeRlFagQzDoUXrv74DkDJ
            UN1pJ/yrnUJvOh33gst7FR0gksLIWb48R4jJsTMKvohD3SO6vJLg7RxCSiJ4DmrU
            aAEJAhD+nZ9AcvXMZEkq1cAHQl02YqvDnORvvS+jrbB6X3KJi67pDx8mSNixWXCH
            z6X3h0/OCYkxX5pUIFWzfn/LiC6eUPiuvjw2a9LRhO5bP0YWYJS110ipjVyF/73n
            e12XYXXH0N/6
            =KD9e
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
