---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models
  namespace: ai
  annotations:
    volume.kubernetes.io/selected-node: brenno-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
