apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog
resources:
  - namespace.yaml
  - deployer-service-account.yaml
  - deployer-role.yaml
  - deployer-role-binding.yaml
  - deployer-token.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - matrix-well-known-deployment.yaml
  - matrix-well-known-service.yaml
  - matrix-well-known-ingress.yaml
configMapGenerator:
  - name: matrix-well-known
    files:
      - default.conf=matrix-well-known.conf
