apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns
  namespace: dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns
  template:
    metadata:
      labels:
        app: dns
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine3.20-perl
          ports:
            - containerPort: 853
              hostPort: 853
              protocol: TCP
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: ssl-certificates
              mountPath: /etc/nginx/ssl
              readOnly: true
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
        - name: ssl-certificates
          secret:
            secretName: dns-tls
