apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: dns
  namespace: dns
spec:
  endpoints:
  - dnsName: dns.brennoflavio.com.br
    recordTTL: 300
    recordType: CNAME
    targets:
    - brennoflavio.com.br
