---
apiVersion: v1
kind: Service
metadata:
    name: dns
    namespace: dns
    annotations:
        metallb.io/loadBalancerIPs: 192.168.20.12
spec:
    type: LoadBalancer
    allocateLoadBalancerNodePorts: false
    selector:
        app: dns
    ports:
        - name: dot
          protocol: TCP
          port: 853
          targetPort: 853
