---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ut
  namespace: ut
  annotations:
    volume.kubernetes.io/selected-node: brenno-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
