apiVersion: v1
kind: Secret
metadata:
    name: immich-meme-detector
    namespace: immich-meme-detector
type: Opaque
stringData:
    IMMICH_BASE_URL: ENC[AES256_GCM,data:RK5ZgVo0swbR7j8Pd+L1Bp5MBOpYQpPyarqaNKvSmBTdzg==,iv:OkVQ1r4WY6cu5aY7RK1BECABok7yyBiFmggFilnGwaQ=,tag:FqQLRry/P0pryxRAXntCdA==,type:str]
    IMMICH_API_KEY: ENC[AES256_GCM,data:6NorLuryAsxUV5TLDbpMD9eWhloPvmNGeDUJAfPjpAvtDlqEk6SEWcE6,iv:WjBktqnTft9JMuMTTsMdgTsc9W99h50bO7wgHLvSPaU=,tag:2XXQ/PNdAIOUEgx/vfbuZQ==,type:str]
    SEARCH_MAX_PAGES: ENC[AES256_GCM,data:Ig==,iv:u3JM64vfvWb11aIM4C6Y7uFD4IPH8RKOlBeswJFJx5w=,tag:20wuy2swCLVd2xMQCSKQbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-08-14T17:02:16Z"
    mac: ENC[AES256_GCM,data:fO1GMTh5/w70T2BIHiLRa5foi7CVtc2muf+1ablKNMnkKzO1UvTCvpz7HAEuagJkGJTlz8qOK4gz2rw7zooa/OlAZpAg1bO2Y7gjN0A6GDAG6zVfM13NJN2CLIebUkEI0iZL5+YqDGB9P7Kr258M6Z1oX0q/zttS6pmMfRTfzAc=,iv:f/qtzsI98cGFaXaDX9lztZbhje4qurfyLYM9s8QJLkE=,tag:3/UlqBDj3QNC9zeYMIqepg==,type:str]
    pgp:
        - created_at: "2025-01-01T23:11:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XAQ/+OeTqrx1W72C2SDD88sg/3Dd1E6XrwU6dsdyYCquIts+D
            eeEETfFJ32xRiJf/HLHH+MznCZ2BXcbXkIAcPJvumIolSUq8KAxoaokOTf4RDic+
            bZ71KPZJmkDdb79CNI7oCGrvgI9jtypW3XJmBgTyD5Ut9YiDvnUepu0494OzEEq3
            UN5t5D8nJysGQ1nXrnv7uU+EwdmSyYJCGeRdR9JmVmXix5lWyyhX1sX6VZrYp9zG
            l4h+y6M5YPQsNiO9qXqG+maEdRVVPAnZbaobKdfrRMmw4/Pxi3Si3s3u57iNwVJt
            dhrMYn65i3oyA47bG+2UNuqbi8pD2F5Auxmv6R+TX2qOc0kO1Ls4E1/o+REP4XCx
            gvLgr3k8CSqpBGm4IeiS8Pw61VAAeJUceEhQNzcGLnJUMnVUlOW8oFR9sSsXPmNL
            mHu4s2gtj4eVWHjq3H3vB2AnDOvMJAmZEOmVMBjGzx8imvubfDw+iJj62Ju9yP7G
            SkgV+RtY3oXx28s0wCDh2jSkMHdeSFVQr+Y1tQTMEBqeDkHnwquJ8URp26UJXAqF
            AOmTdtEXtMXQ+Q1Vj0dadUnBYuTH/2DN3j1ELI/1fjKw5H+57PKz5Sa8S5ZWxWa1
            3ENkkWT5Q6wDMg4ClzNxQ1+BqWWOZApH04arwk3yBL1kplYaatLLUTW3pE/ghJbU
            aAEJAhCIF1dyR2tCPQaz4fOU8KAT6zbep9jCEN0tMNPu0EHvyxxVRbvAALfvw8SZ
            B/Gerl31JVX53agiN7fnytPAm8ar+rU/t84hBiOQ5X0XX3ZM/nbCqmWzs4H9MouQ
            idT5Ypxx7P6x
            =NMKt
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
