apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: silverbullet
  namespace: silverbullet
spec:
  releaseName: silverbullet
  chart:
    spec:
      chart: "charts/silverbullet"
      sourceRef:
        kind: GitRepository
        name: silverbullet
  interval: 30m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: silverbullet-values
