---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: silverbullet
  namespace: silverbullet
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/brennoflavio/silverbullet-chart
