apiVersion: v1
kind: Secret
metadata:
    name: registry-auth
    namespace: registry
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:qlBtFg65wtc8pzwRag6cBYkCTeOM4r267qKCztHMZ23T+JVIPGiH1Pg7P/oul1CoclcrPiXB21NHrtD74uNZrGHKGw==,iv:NOFTT85h0J+Q3JmdqtDwieKxjO2ql9/5DK8VObZJ5y4=,tag:PTciFE5VF8rTtT52aclaUA==,type:str]
sops:
    lastmodified: "2026-04-07T03:29:16Z"
    mac: ENC[AES256_GCM,data:Xc4YoECvmUsRPTmRM7vE92PD8FBuat8KhxFJGbsXpN0EuA26aSvf3pIlJ/ZUnwib0MZYvhTRre9tcJx5lKTbgue8YJtcqHgCZubCs0NPtxUaDtdi/FC2Bw1LBT5NhtBhPC+TThQLmqkEGFLK5KxnFMNxJvm0RWoHzTl5mrJE5II=,iv:Xc6L1rbN2DI7Dk1Scb4LNz/xIqJhwSz8L/946Uy4q0I=,tag:ZSOGWTISlcJWAYVmXIn4/g==,type:str]
    pgp:
        - created_at: "2026-04-07T03:29:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XAQ/8CJsjqPXd1qF4X3nMQKVVQrxBqY8lavO8bDb3MU+G0lpa
            wuW/68RBjTvKB3q6pLgM1VLbvbCnCj7rAt9mvAzciEkureInwrSR8P4moq4VR22j
            7HeVfKRsFV6ySHlRlEpAxR9tlf9y7frUCEIYLW37WfxcOziLmIpDlZIV+q7SpbqU
            lVkxNyhu93rF0onbNN1KqZaruPKkwfmVnNaau8a9S8YN4qErr7MFTwC3H4eELMic
            2zLu5ZKGGLSv3blKbHmXjBnPfK8J5gfz3jKcQPbBuyZ2l+KY4nhLlZDJDb7bG1qW
            pAtEy/Ei74TtNUJc0KjN8IUqbIllM32ZSV1qkAhwDJanSgwAvu2ITls4+nmcZn59
            VTxa+R56a3/brozHX2Ch3O5NH7SoPCiDAEachK87L7qwwZOBo4tdIEjC7kC7bWhA
            +AalCksAXKqrIIcb4cbVXt/HzZpmn+NX08WvPgqcug71e5/aR2/ldxlsnPOpKRsP
            8wgjadTsu/b5QCRDU4xwsjSfv7IZpBtQaaxvg3awesHogdxLbI6HgUUIWRPQpUwm
            Bkn3ltOwlq7quPrij7mcAQ8orylvbhj8Fm4fJeWvY60FBNUTFpAxrqtqUcQyoVlA
            oH2xCCO6Um+gYRHub/DY5SIjVMG3ovNFMkpVsHX3ZmLURhm3cAUJY02CSNiuPDLU
            ZgEJAhB//nirT4Rmzk+8PD9lMa0wtX79n2cEjMn/tmoEcE2wfOa8mCn+arXn4fKG
            Ja76QtlXcE5xlX51ZPJBMfg6hjQ4hZHuMRMaKUVJMT/kTEdBxfT74WfYyvEIB+tN
            tJ6SoLIX5Q==
            =UlTn
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
