---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo
  namespace: forgejo
  annotations:
    volume.kubernetes.io/selected-node: brenno-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
