apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: forgejo
type: Opaque
stringData:
    FORGEJO__mailer__ENABLED: ENC[AES256_GCM,data:NwYtgw==,iv:kMGdrF7jHhgD6TLz4isT/z0Eeists9GNh+l29iT2XOM=,tag:yOxElIG8JNrqDDyrRsufVA==,type:str]
    FORGEJO__mailer__FROM: ENC[AES256_GCM,data:MlK9wVWpWTTObtmDOiHROvb1PCEXW8U=,iv:OnnYGshs5piY86eFJbdTS0IruqutiaziPUErbs0xeh8=,tag:TkUMUNtj7+ILO219M88xnw==,type:str]
    FORGEJO__mailer__PROTOCOL: ENC[AES256_GCM,data:occFYtOMDJFm3izh5A==,iv:Z02ckKnTMJVuMQZv+cgA55/QkY0G25tG/B7xPqZD50I=,tag:ieNSdwyUnuV51sqJGMNMOg==,type:str]
    FORGEJO__mailer__SMTP_ADDR: ENC[AES256_GCM,data:N2XfMafHdxCymNUWL4/MLVnHdb2yStro,iv:2v/NeQriTJ079Sdd9oJXg8ziqasJ6NVNAl3Ne6TniC8=,tag:ekRG47DNRPyuTtm4HXOeTQ==,type:str]
    FORGEJO__mailer__SMTP_PORT: ENC[AES256_GCM,data:kJKt,iv:ndUGet4Mq9XH98eUBCS46pKxKdU+tzHZcN5hQ/t62zk=,tag:0iwNrUysVh8n4qDC49r2cw==,type:str]
    FORGEJO__mailer__USER: ENC[AES256_GCM,data:QjL1WdeG1Hht78XwJnOX2yW/Z/qe64c=,iv:Yz+XpEX89knsZktjAe5PRVD6lux2WhxUd55Gxcg79f0=,tag:rWbIsfUsCHf5WSILbQE5nw==,type:str]
    FORGEJO__mailer__PASSWD: ENC[AES256_GCM,data:XOGv/ZLsAO+9Tkdxio5mRn+lGPsUTtDpO6lwzqYLhO8=,iv:sEYkXsSaJ79Ds3m0Ogs8C5sV8s0+grQNAtSuJbE48zU=,tag:yxqOoArsPRGjmY6LMyxHXQ==,type:str]
    FORGEJO__service__ENABLE_NOTIFY_MAIL: ENC[AES256_GCM,data:9Qc+LA==,iv:AJJVtQU/vTBok+18dP8r/z554VXlDQu+Co6Fr4IBctk=,tag:wi2mBU2XiSzvFefX1huHqw==,type:str]
sops:
    lastmodified: "2026-06-15T00:53:58Z"
    mac: ENC[AES256_GCM,data:dweuJ226rB7K5QYH57yUOXHuEV7jxiQvkiIDFYzm7I2wqC3WoCUNouTV1DJHvURpQGh8zdD+/WIyp2VqQOlOi4cQCON885tMFYu48C5VBrz6h8y1/2iHiMsA6gXUEmaYyANEHTe7thb0q2Uq2ZzEhyLgh4wsE+/eRj4SkHy7/QU=,iv:gP0Mvy75LDhNKngYNqU6CQt7UCR3xLkFg4q1bCnaOQA=,tag:OC/7P4XqCtyvAF1VDk6hHA==,type:str]
    pgp:
        - created_at: "2026-06-11T04:05:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XAQ//VDr6fELNiuxhehKPjhiMkhwpGmmiXgi3K/wPqakNq/wx
            Z4ryeJCtuLe1y5QsI0YsK0qR3itCkvzVKjXK9vvPqjPSRA02JxH73yNpBXEEj0nq
            bfLLx1aP/hoiRlqFvX8phzesnWhjOY5qgZHgYmrOVHyI8FLdj4G+5gxA1i7JPZUH
            DD4VQWXINBoWov1l91mWIevy92j6OjajE1yQdd4ME7+P4gr5DWSpzZhyv2NjzcI4
            5X4FSkgVNrfdx35h3zdI59V0O/BiNfPIFT99ggJOBpkWuhbjw9tcYP3ARtO0Z50T
            r/a8zSq1d27K1/rQwC5TM7WrWu1/jPlQhZXGPnzTWOQEpUk2kyTrgmmOI4zAYtAh
            t/bAlnFYCQtf982oP4od3b+sLSDWN9fh7IDgHpMRR2yOlC3koWlIu6DWMUsS1CeI
            5enHv5n3mMnNNzLuPtVw3SoIKWz5nj8iPij50lTzjdIrkCElpvQRHzScKcnLdxNO
            YGy56DqwOMdAQybxxJgAQqEc1+ysNsMI9pqnB0DuXaNHTEn/ZbT75kFN33NfK1sp
            pd/jhVKxNpXjkeznOIPcx18ihlh24QbzBMNH+laIxeokrnqCe8x7m7noifA2g1fu
            gxGFlQx1XmteGwqHpANohGmvau3XQ56FQIbftqyPLj54qeUFs+DLoGZSNKDzieXU
            WwEJAhB/maaRdAQ9/qn+34F6r8SnqfMjXHMYhNrdM3XC9I+J16JDLY5cPUi9fPJv
            ZeOGqApoItI7s5ksoDz21GOIFDSAS6+weE/sVCsJ9wYY4xi412fH9tdYmJA=
            =jLnz
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
