---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
    name: backend
    namespace: minatto
spec:
    image: ghcr.io/brennoflavio/minatto-backend
    interval: 1m0s
    secretRef:
      name: gcr-secret
