---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
    name: frontend
    namespace: minatto
spec:
    imageRepositoryRef:
        name: frontend
    filterTags:
        pattern: ^master-[a-fA-F0-9]+-(?P<ts>.*)
        extract: $ts
    policy:
        numerical:
            order: asc
