apiVersion: v1
kind: Secret
metadata:
    name: palworld-settings
    namespace: palworld
type: Opaque
stringData:
    PalWorldSettings.ini: ENC[AES256_GCM,data:szk2DpWGHQ5NoSxga4+eamD5wzLb6A6tZkyMWbz55htFe8zWUnVcrXnYyXOY5UeMb0TISwthhcuAXBWAoAhu7TyjN4w3mKwVfKeZs+FwvgfylBH96LCbw9yd5xBY1zDwl1BlFqqXucp707MpEeFBdeOCdb2Pbz25Zu/EpmvMa1YnN7t67rIjXzkkXaHeT3EWCEDoewpl4qX0DY/Ewqvf2lswugPEjuaJVlDlbyazdSICzQSSa76wY4bY7FsNQPv7dzfRnRKG+SDjgs9Qqm/WDeKghdHWN/A5V5OU,iv:DPAz+fIU4SoJ9zB5nfIe/E3qnZXHYUAHkNwtbQ9SiF0=,tag:WjDMRLJZOXADA5xbVx2viw==,type:str]
sops:
    lastmodified: "2026-10-03T04:34:49Z"
    mac: ENC[AES256_GCM,data:LfcVMRkRig+vaxjwYI56zcwYouVjgoFt8mxCQyN51gHsDxJJZjIpoCmxULmeYi6DzLRPIC8kCEhJyHUFkBU9hc/53teybfRirgNTFOPQhLLHQiVHow+/SbqwVzyM9SoqY5JNMC4FvEKFoFpXcWU+erYu5JjbL6K3J59fas+pneg=,iv:JwwZJ6HCTP+M/9EiL7Zr01oQf96jfr9pxObGfjOxQPU=,tag:OfZiE7V+shuPiZp0sy3Zug==,type:str]
    pgp:
        - created_at: "2026-09-27T01:33:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XARAAktUwW74KubRN+H6mk1YS7KiBgXIDjcqrgd7EANezRxFp
            2qgj35j1th3oaZmJQabRtu8vdMfy6HdhKmANyvMQnaWP4k5pVcBtFEUdp2XHy2Ss
            +3nL5Nlhj+x2h81kCOqfvdKUk/hMquNYtTh4REO0RByaWN2TuszgQ2ihsq0oj+ff
            MHylWzpT0vZtGbJM3GyQFJ0B37oSzaV713wOrhb9fA2dzEOHhjeN47vNL7n9V5Jv
            3NliefRBkpwtD783ChVq3JGmOtu1+/AZcau/OT5Z1yznzRkQJUTEe+6YBITY3c7p
            x0vG+hLkLFZ+J0oV7ycEEi+s7Uld1iOywfghe8Al9Gvgity1u8+tRJ4IxiiuPElM
            w/N945df3fFHrnUGs8/ToNkwIAEo3CF9vebDLV1JKaybz+qK3O4Gnhe9Yfw089i4
            cUD7csS586Z3xwJXkrKEAGzleLs56HURAuSNLlDOpd2qRYWfkw5ETelUFck3Wm1i
            uSI5Mdali4fi6TQ9f93TIt1gRKYxg4dEPD4UN9qkRQS+g8gaMRkzImWdGA7tr1nL
            v0OKlLf/DezBGQxHDP7tCVn0QrF8+M+2vQLNEYGMtMtgIXDxWtJCq4/sNspRnEX8
            OwQTnmLHF13w9hXAs/Gem0FNw7Sds0wWhU/AY+6eABqclv3kHEAGwQnGNjD05HXU
            aAEJAhCsi4X/yt6kJmHLAMuqoYfGPfbOKX9GgbbHfqQqmw6gez+gybMMOvY4PikL
            Y2HFCK4Khse7SC9bDCi3EVK64OhKiliCPGeC5Vlqvz3eBu9KZinbGKdvuVP1pERn
            5Q5f6VsKW427
            =jxUu
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
