apiVersion: v1
kind: Secret
metadata:
    name: palworld-settings
    namespace: palworld
type: Opaque
stringData:
    PalWorldSettings.ini: ENC[AES256_GCM,data:9gKYH22MfDDULYhQdo+potVk7I5QLFWIFzToZ/3cB/8j1F8R77QSn9Tpo6gXqHX/ZrQ43Uyy7hL6/wZXOnxTiA0Rdq4Bax+hAANCq2PZwVN7tFAoW6VJRAF/cWTBoNwVBESre0peka10RFpEnYUvdtCSxSLaZbrT/AwJKLnQ+ahuSSeQVwe6NtO4hF02Ajna3k7+o/gW5YbMwdGjqsZT6wWIS9w2qL88VTke4Grng7o4pgjvM9V2z1JLB9oAoEn1j5I=,iv:icFEYmG+ur9tEL+BEfowfU6auqlZUCrnnreCASTlvvI=,tag:VviykCGDefn0F3G3aiBZwg==,type:str]
sops:
    lastmodified: "2026-09-27T01:33:42Z"
    mac: ENC[AES256_GCM,data:yG9sRfPpIX3PwrM7UdsAm7LovaYpploh/8/C2CjgGPSONRmP8onnobXg9CHoNyrXsGRqjHeBDvz6qu1exJbWHULpuJn3Tgz0GRniAVb8aZDZuM5JJLOt8SKyi4z/kdKgYY0P8UivnSq2tWySNzXuVlcjPNR54sStP+ptB9NoxgM=,iv:seZuJvX/YRDnlzDUfC6w9ZQNrWX7cTNW5ThYvkTxW1E=,tag:iIzWPBdQYRn0yhc4zd504A==,type:str]
    pgp:
        - created_at: "2026-09-27T01:33:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XARAAktUwW74KubRN+H6mk1YS7KiBgXIDjcqrgd7EANezRxFp
            2qgj35j1th3oaZmJQabRtu8vdMfy6HdhKmANyvMQnaWP4k5pVcBtFEUdp2XHy2Ss
            +3nL5Nlhj+x2h81kCOqfvdKUk/hMquNYtTh4REO0RByaWN2TuszgQ2ihsq0oj+ff
            MHylWzpT0vZtGbJM3GyQFJ0B37oSzaV713wOrhb9fA2dzEOHhjeN47vNL7n9V5Jv
            3NliefRBkpwtD783ChVq3JGmOtu1+/AZcau/OT5Z1yznzRkQJUTEe+6YBITY3c7p
            x0vG+hLkLFZ+J0oV7ycEEi+s7Uld1iOywfghe8Al9Gvgity1u8+tRJ4IxiiuPElM
            w/N945df3fFHrnUGs8/ToNkwIAEo3CF9vebDLV1JKaybz+qK3O4Gnhe9Yfw089i4
            cUD7csS586Z3xwJXkrKEAGzleLs56HURAuSNLlDOpd2qRYWfkw5ETelUFck3Wm1i
            uSI5Mdali4fi6TQ9f93TIt1gRKYxg4dEPD4UN9qkRQS+g8gaMRkzImWdGA7tr1nL
            v0OKlLf/DezBGQxHDP7tCVn0QrF8+M+2vQLNEYGMtMtgIXDxWtJCq4/sNspRnEX8
            OwQTnmLHF13w9hXAs/Gem0FNw7Sds0wWhU/AY+6eABqclv3kHEAGwQnGNjD05HXU
            aAEJAhCsi4X/yt6kJmHLAMuqoYfGPfbOKX9GgbbHfqQqmw6gez+gybMMOvY4PikL
            Y2HFCK4Khse7SC9bDCi3EVK64OhKiliCPGeC5Vlqvz3eBu9KZinbGKdvuVP1pERn
            5Q5f6VsKW427
            =jxUu
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
