apiVersion: v1
kind: Service
metadata:
  name: palworld
  namespace: palworld
  annotations:
    metallb.io/loadBalancerIPs: 192.168.20.14
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  selector:
    app: palworld
  ports:
    - name: game
      protocol: UDP
      port: 8211
      targetPort: 8211
