---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: backrest
  namespace: backrest
  labels:
    kubernetes.io/service-name: backrest
addressType: IPv4
ports:
  - name: ''
    appProtocol: http
    protocol: TCP
    port: 9898
endpoints:
  - addresses:
      - "10.0.1.1"
