---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backrest
  namespace: backrest
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
    external-dns.alpha.kubernetes.io/target: "brennoflavio.com.br"
spec:
  rules:
  - host: backrest.brennoflavio.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backrest
            port:
              number: 9898
  tls:
  - hosts:
    - backrest.brennoflavio.com.br
    secretName: backrest-tls