---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: endurain
    namespace: endurain
    annotations:
        cert-manager.io/cluster-issuer: lets-encrypt-dns01
spec:
    ingressClassName: internal-nginx
    rules:
        - host: fitness.home.brennoflavio.com.br
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: endurain
                            port:
                                number: 80
    tls:
        - hosts:
              - fitness.home.brennoflavio.com.br
          secretName: fitness-tls
