apiVersion: v1
kind: Secret
metadata:
    name: endurain-secrets
    namespace: endurain
type: Opaque
stringData:
    DB_TYPE: ENC[AES256_GCM,data:IrafTo4qq4w=,iv:/bEPs2sOecy4TePaxq1bANX8W5cGHVTy+mYWxa24440=,tag:1n0ZRktpMVeRRNIS6BaatA==,type:str]
    DB_HOST: ENC[AES256_GCM,data:Fr43DNBdH5w=,iv:mcxHx1n5uu+SKP7FSCc3ZQS57JjNXNCDiXZU+jJJzEY=,tag:ldrF/ugZ5FhNGfWvi9yMDg==,type:str]
    DB_PORT: ENC[AES256_GCM,data:MvD/xg==,iv:9ytKs6xv/Am5dXm2nbiOdX4oGnJv46rYIM/+PoDBh+U=,tag:42x9TiYweaebIomX0iIyWg==,type:str]
    DB_USER: ENC[AES256_GCM,data:Npb5jLcFskk=,iv:p86V6ZUMHHDLwTeAGn3hAr7AZ4X4m28tpb5+M9+ZgiE=,tag:7IWRg0LoT+gR334k7yt5VA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:nxBYFASG2SKa8UOLMNaJukHMghNb6sGUXzxydMqTQdI=,iv:dT5Fy031GIpn3OqoaYGWpbuA+/n9ZyI4mQSO3cGzzXw=,tag:8Tt1l9qjsPPOJLffyEk/XQ==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:Uv+zvt6Ijmc=,iv:9f6gkrKrFZ421yZ/QrJJDc5PCmmGLcR7p7RJlwOJjNw=,tag:3SQqYy2VG4vmVDirJl7lOQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:9RxUFR06ybY=,iv:xN0ykOifrXNpv0UKdkKxpoY+IX0Bk40x8vCr/O2pQKs=,tag:tsmz9eeXl1ghzmAwA7KZRw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Os3A4BaUeVkrXdd8RwPh2UfoD9M/6J+WXua2XomN9Q0=,iv:2hfOq0R0gxqvkL/rsu0O37NkSuVpIAWV6oFTiMjkrOk=,tag:kNqMadReO+w+0TVu/riTWw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:xxG++gWECFg=,iv:3hsH9aVn2nkze7r2jDR/SV1kV9Q6YTgFmJoQFoBmaXA=,tag:xc+BcgEYKg4RB6JrH9GQ2w==,type:str]
    PGDATA: ENC[AES256_GCM,data:sInUGa42nkFYenK4KAypVYAeX4+wDdhRMGKZd40ViQ==,iv:LOJlHhvpysUqAfagSg/nqW9nfAlW2+tRstIg88HiuJg=,tag:t79Fo6To/b3P3rsAHzqVsw==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:B8cZLJZ80nI9DjSPB7csPsYMUphz0XJFLnv9fWAOeCm/O4XaSjHJqylhGzCXS6ZbUENlP502aEVBuWpq4nG69w==,iv:X1Fb5XeZaSDnjW42VtK/5ZzmnWCbwmv/7rR358+9Byg=,tag:dUzgem0w172ZuDbQBRUGfw==,type:str]
    FERNET_KEY: ENC[AES256_GCM,data:ysTbUrZN8PN/p4YH+M3gLrY5M41dBd3yuOVlhHbYvU/FU0JWQ1QBTb8bjSs=,iv:PkzIdOVsb4jkK9E1hg3dt2Jkbvk6TYeJAJjDgGXitVg=,tag:ds7gw5Hjm3Q9rxaVBbS4YQ==,type:str]
    TZ: ENC[AES256_GCM,data:OVIEMNx1AuTn0KJsuXcBZag=,iv:x4cOtXfLwLiib5Fd8ydEUHtDNN/CyAlXndqrPAIqVHs=,tag:SlFz4ChzwUruP4sWUL02mA==,type:str]
    ENDURAIN_HOST: ENC[AES256_GCM,data:JHZHnKX0SSB7PPuR/8BoXLsJ87EklHfOoudsjoLbEWz4NwM=,iv:sO34Npp04TyxsUZ6hKoGYmJPzhKjWSTDiN+lKEb+3kc=,tag:WRiUwLJfLg2iyvg/aJkGpA==,type:str]
    BEHIND_PROXY: ENC[AES256_GCM,data:85IkRA==,iv:z2xAmhcF5SoTioOZRsU5tpVEz1YUZmx9nW1cLAR0qUk=,tag:aordVewZtfftUC+g2uhceA==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:cYrt1YsHvPy8FhtuUTK5z4sIro/ts3DE,iv:z4iLBLcPTpBdFcGfocr+roOoXBQGRs6lUeKdAxyEDaw=,tag:qTrRVKpOpEYGMCAFLUwHBw==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:v2cK,iv:7jz+e9F47T3BasBWTsWTeC9ZAWh6e9DnbDJgtV9vOr4=,tag:xoDEtw+gxX4mlkIoBQ84IA==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:WU3JA8YenWi5Z9Gw8UsR1mmZoU46LzDOUuZ8Jw==,iv:ypMTWfcl8xdX+YVydG30usSkO4Wqo4LcgYWCnf6J8NI=,tag:gSkIbnGhd0f5ttFY4qU1jA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:VyvL/QYOQ8a349hvzkRsXUBHWcEJLJAX2BUIFeQIM6U=,iv:MmxRwyQdlSwD/3DsSaK8zkw30bD9BsjcEIMEaI1kUlg=,tag:QLVDSNQQHoYfiBgIpXW9zA==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:D1ZwarHqc2n5OwJKjG6HnslW+ibwIJ6k38c8Sg==,iv:kzhd6VGBv5ZxpammJ+WzYJQvGkyLCgvRGPkmWtkCymQ=,tag:Iz6C5chtymbYKmxP7WvDUA==,type:str]
    SMTP_SECURE: ENC[AES256_GCM,data:v7ccKw==,iv:bb2bxrOSlFhpdDlER2g/bpgZFOhWm0BfYikRyjLmi7s=,tag:qAzmRUftzS0DEHPnIcRwSQ==,type:str]
    SMTP_SECURE_TYPE: ENC[AES256_GCM,data:c/Hb90zVWA4=,iv:w0/8BWIdViVuUcOWscxCXdJxHmoOyWTgfAhCzNp3WsU=,tag:Dp6Wzy7OAMBnO5Wa7N7MNg==,type:str]
    RATE_LIMIT_STORAGE_URI: ENC[AES256_GCM,data:k/rJY7W6i8lFWL6yELHfhBE/jes=,iv:mAhSD2vJd4U7pZw2RhmOQjfZSXZZ8KdYhWValSZakV4=,tag:XLgvPEOtRtZYdT0gScrIoA==,type:str]
    AUTH_SECURITY_STORAGE_URI: ENC[AES256_GCM,data:wHKfT2tXk8Kqp8NaGlP9dsWj5Xo=,iv:S7a5goKzRH8Uds4CNCGMPub9F6Hl7xG2XWPAdedyUHM=,tag:EfIwICGU7n6Er4n+sWhaTA==,type:str]
sops:
    lastmodified: "2026-07-21T03:33:46Z"
    mac: ENC[AES256_GCM,data:oeP8rMwaelzl5VtkYVl3GuRhg3HfJIvUd2C7dQNUBdffM4kEIS2rOntIlYOHRv41dDHv8VL6YbQbnGqdTQ2zLVZX97G/Rbxk3xj4NLhlkWtvO5gN0F/dNtfHTnCqClC7L2vj7hQa8vI9+2vAtWAUEq6YNDrQGvfTVNl18Hfp6Zg=,iv:4joD4sp2tCTX5xs1yQB6Wa5MPI3b8MOG6xogCykf0Ao=,tag:d3TXNstRzUXWdZvyxwJeig==,type:str]
    pgp:
        - created_at: "2026-07-21T03:33:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XAQ//To9eoyg2wc+S/CtYxKkZhr1aQLW9dS1UI3MxfxxPdoom
            YXJaabZIiJyxPqB+vvAesWDJCTalKLSzdfPLgJuj8qjGHOG3mJVTZv3ceF9KBRix
            RY6fE6UFaYd2xNdVWinV/MA8Ws4gfhHsegiNZ/+z49Bgf5MutqPAF6CT2jBI+lEL
            R4bJxZjwUCSw4MW29j9G91T68z5bF75hhu77J0r3by77pVuNb3FV89SWxRKbbzRm
            903ih2krCINbKcg0k8r+0GmfrQZDTuG0/YLGvb2o4an4Z+doWJJOkkG0fRXdQkHz
            kD19xQsTwjCQMOqAC7CiErtxcphfwKeLMavCkhF++mEfXg9q0TTYcbXJJA/XTUf4
            qUOiTObwrWr77B9TlFa7kXKWycc78EiyOJFeiBnd44kbw4rmDns0VxnnVYZXiJqY
            lEy88lg1C7iEfByMKOUQqQ3mUFgteVqeE5EOwksGNW93H0qyVko7EkkfMSsXYr9O
            zsVUvtc7DKF+8zRrlmnuw+8pPC1ir1reTHZ48ucnAyd6mfzhsKm/JGrEfD+1QxWi
            kUw3M1qswxD6gL+XXHKMXBlHXiuCkTNelu955/f+IGXxG4Nhz31quFcEfIA8R+dV
            LvMQcEnNvIKXYSLG9Yk4fqrEXUCVLzPZCT4i1xsNN2o4EC6shOURzh+3GGp4rKDU
            aAEJAhDCVvGj5Rt7G3Af0JAcKbZEv+gp7yaUCNsyZqPqDauH7JOFyYgZD/ibnVOW
            sCn5bUm4oFXsdCn4ZtmVLqRyxVDvXRbDw3gJy1XFz+eZtUWOCWO9J/TAaGsppMYY
            Rz5qH7lLudAo
            =KWO+
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
