---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atuin
  namespace: atuin
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  rules:
  - host: atuin.brennoflavio.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: atuin
            port:
              number: 80
  tls:
  - hosts:
    - atuin.brennoflavio.com.br
    secretName: atuin-tls
