apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atuin
resources:
  - namespace.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - claim.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
