apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: github-runner
  namespace: github-runner
spec:
  releaseName: github-runner
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.13.1
      sourceRef:
        kind: HelmRepository
        name: github-runner
        namespace: github-runner
  interval: 30m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: github-runner-values
