---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rimgo
  namespace: rimgo
  labels:
    app: rimgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rimgo
  template:
    metadata:
      labels:
        app: rimgo
    spec:
      containers:
      - name: rimgo
        image: codeberg.org/rimgo/rimgo
        ports:
        - containerPort: 3000
        env:
        - name: ADDRESS
          value: "0.0.0.0"
        - name: PORT
          value: "3000"
        - name: FIBER_PREFORK
          value: "false"
        - name: IMGUR_CLIENT_ID
          value: 546c25a59c58ad7
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
      - name: anubis
        image: ghcr.io/techarohq/anubis:latest
        env:
          - name: "BIND"
            value: ":8080"
          - name: "DIFFICULTY"
            value: "4"
          - name: ED25519_PRIVATE_KEY_HEX
            valueFrom:
              secretKeyRef:
                name: anubis-secret
                key: ED25519_PRIVATE_KEY_HEX
          - name: "METRICS_BIND"
            value: ":9090"
          - name: "SERVE_ROBOTS_TXT"
            value: "true"
          - name: "TARGET"
            value: "http://localhost:3000"
          - name: "OG_PASSTHROUGH"
            value: "true"
          - name: "OG_EXPIRY_TIME"
            value: "24h"
        resources:
          limits:
            cpu: 750m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
