---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rimgo
  namespace: rimgo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: lets-encrypt
    external-dns.alpha.kubernetes.io/target: "brennoflavio.com.br"
spec:
  rules:
  - host: rimgo.brennoflavio.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rimgo
            port:
              number: 8080
  tls:
  - hosts:
    - rimgo.brennoflavio.com.br
    secretName: rimgo-tls
