---
apiVersion: v1
kind: Service
metadata:
  name: rimgo
  namespace: rimgo
  labels:
    app: rimgo
spec:
  selector:
    app: rimgo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: rimgo
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: anubis
  type: ClusterIP
