apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
    kustomize.toolkit.fluxcd.io/force: enabled
    storageclass.kubernetes.io/is-default-class: "true"
  name: local-path
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: Immediate
