apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: gradus-gtm-coding-agent
  namespace: gradus-gtm
spec:
  image: git.brennoflavio.com.br/brennoflavio/coding-agent
  interval: 5m
