apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gradus-gtm-home
  namespace: gradus-gtm
  annotations:
    volume.kubernetes.io/selected-node: brenno-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gradus-gtm-data
  namespace: gradus-gtm
  annotations:
    volume.kubernetes.io/selected-node: brenno-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gradus-gtm-state
  namespace: gradus-gtm
  annotations:
    volume.kubernetes.io/selected-node: brenno-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
