apiVersion: v1
kind: Secret
metadata:
    name: gradus-gtm-agent-secrets
    namespace: gradus-gtm
type: Opaque
stringData:
    PI_SECRETS: ENC[AES256_GCM,data:Hx6YT6DY1NVHDYvkTJUGAZInBwEPVGHCRbZtLJv6V4PghYR3/wC0JOsvjm0rd99IxBSiOKzX1ENo/owODB9kWz65HaS5RhkR+cousmBIZrxw1GUoq8e3jjT6iERJyWpHt2DCPeWjlGe2hjmVRIcHwPm7Sm4n4eJpqzF6WXriQKmiTRhDWHpxMbAydbfEkW4Jpa3/ps26457LrHWDMMjFoyz8u3dN9tibH80/UT90EHgmYEdJsSRe7xwinfs3NC7JUFNJr0HauNGXdqZO0BxvNoQVDkTdl6lknTyMmPWr8hh9j09A/oDtabDxi7sYMmKucX8VrrTzy+zkXgX92Epjj3VugI/Q2l2MfZDKy9k9tiiwI/iXym9tf76jqA06whpzTQkCCSt6GknnJJOkS6KvOmnOls3c8Ek36BWD15ItIWvG7xSNsuYH0hdF+lqbe9ToPqziIpoNWLnMbboB7/y0pBaZMk3Onf5ee4I802Oz59yl5kjs7Ri0R3D6+IXCsq0tuZnA+O94e/Q6ciaX36i/5JVjLvzp0q/Cq/7G7du8GJi2MrGcXDodX0SEOn5S3il72yTU8p8dF0yHeNcoWJjnRfVrGcS5XvMKriUwohrh9jnPHZMIKFXgvXxGbJGeuLLK1NxW5QUwZZ2D8nIiBjkVW39mOR3e7sl+IJqhVJuBHXxfcgFUFWsKuw==,iv:sIO+0VPxlYSjDHpsmtk5uHw1VtSOvwf1f7ljpyoVr1g=,tag:TF3qw64jo2u06YIvP/qEKw==,type:str]
    git-credentials: ENC[AES256_GCM,data:yy370dstKBTozOXblaFLsgyzuGm98DmdOddNG9MAopxWmAI23l7iqEmmxJnKuR01017tMQy5t3tvR0nX6tyy9MsoogG3qXIMXb9KOOJ9WPtVuX/H9eY=,iv:cEbmcKUqyLg2hK05AQXRVmghN9ZkzNJUbtVXdsG4Ruc=,tag:pX6i0EFV/ZeEFKVGxiO9mg==,type:str]
    PI_TELEGRAM_CONFIG: ENC[AES256_GCM,data:zsxNsgnd/D7SJMvS6YN9SEtkKg8NTumCWCWDDFUyVrNMRNi2ET4ZtV/7qqV98F8bjYA+eGSKAhyMku61qqml8BEW9Uf6idwAD8m5uPxR4iIlhY2hkR7j7WbTkROz3Rfhn4l/NiE27pGf2q8WdNV4N+tDTEds+y0+AHe5EKNA7XlEouT5gyZNUUYv,iv:0YwhFqs5LCk2RBPya0yD0cOOhMPeiha84ApRZJyuvSw=,tag:LCYu1qPzRhf5xnOI6wqIeg==,type:str]
    coding-agent-config.json: ENC[AES256_GCM,data:WwL/V30T6UmYfM0FpbjQoVEtteiTqccJdDXmiZn/70pDbBatQIQzjPA78iQvs8hulZhR/RpCONlQBH52BIyegyiiemEbonGgOTKFnqU2XRIJN9vsHOMi+rCHG+xMEdpqp2xAdIo1xNHrEZhCEaeHd8cTdRYMV+jayGB8jFWsmCnzh7xJ4SiX7hM0LDByZ1Hx9rPtzzGImhm4C8kyYPP+X64mSCoN2qa2Cg3DnoYsGrjZoPYOOHOuKSuhqnNR4UecACl8aT9z3OC4OJmRrA60vp2vh6S2+yHUsTsjrVKh5ZxtbNGKYrpmdh9voZLvh5k6hqTAaukwyeW02O5LqeWXXGHlglDhl07keTh6gdXZ+I6Rfel2RmYlweaMkXpQfrI7cdaAd8FP+FgNVGC00rQVW7TZOXMr6KbDEVqE2lGYawzPSa4CInUJKAamX/dZca0Uy0r3djPZXZRAWsSRtCrd2ffMiFvIS9LDmsBJFahWQ3YtJhcQ2iie16ozpCfoAc8EfvyLE7lRexwsxTrIg+e1gRZb4et8roA1SWYMtYNP5GBQo7V3nyZF+heshFwdbeC6jgEzcv2O663jiQ7alHphE7Pd9ZQIL8wbFqxapQjqFU4IPjWl/2+afERUsS8Qwub1op74+e3TxJJiZ7O/wB3w0oUNJuy2MvvvM67v44sTzLGcq6unFrhT5qFSyAWajc8ijBZOiIJtF1gP66ySMnI9uHG/5QDRfXHo3ttWETjdwaWs4PvZZbXtV0lECrMlt2CpWQNBFmZnf1jVlCfTvza9FaXDqOM7AM01z3gCnZwnOPkRSPG/mHp3XXR2atSaZHLqkQsvlkni8NhADCI=,iv:Xkdtow+UwKOukPZSJrWQXzE80z//OAYeJCh1ssoQp9c=,tag:hf6ukGdh2zydCYwisyzUMA==,type:str]
sops:
    lastmodified: "2026-10-09T03:52:57Z"
    mac: ENC[AES256_GCM,data:e5VHs1V/lYveTaUPMlxCDgm0kF9+XORv/omN0ZTy3TLJOLytssPvrVRa/HxJ1VX+Ie9r/sLUR4eAn+9l7Rq8qRt8XIKjja8Fft3WPw+Z91+/lkLdBb8xhErSpGtDZsIiKBXXoB2XpQFRnRO2r6ySQN6Lm9H3iKrWM/yF5UpD9lc=,iv:eMH9hnIP3NEx7j3kbUANTYlPKq3or1xh3jriIOHmO/s=,tag:4QzTB5G9Rif1S/C1WPmTpw==,type:str]
    pgp:
        - created_at: "2026-09-30T05:55:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XAQ/9GZJlPeJPKE/weEk86fxAXnZlxVIekvvog7mZ7zt6wzS5
            WbD2EYMI3tIdqv8YnvNQ/Y9Bcsqv0YkxHBSSPfB1FcxTaEwWU27LqRvjiAfh+Fg8
            b+eHbVC9AGoc0++o1beKEHs4Ab9a8BqlEZB5hT/D+gxhhTLtOdP1z0E5jf239q0l
            +EH5QGmwa0ZmeAXjibkBx/wMnAf9b80pux4h4/WRDzFcPkfPks1eSWGEBfMyFhSj
            GoF3uV2cMql37RLLMqc31wv4Cf98bzFfX4EsQPdrYhXRSBdNIDkH5KAn9KumEBpe
            L02vO4QQTeC15Nf6ypXoyqEzVEIicIy0014SZ7e4x5RYPfhGGz31ZEErXFW8bxa7
            fc95OrNoqldohEsDaUHfsgnwF7S+nlw2isfFyYVFuZTKZ9iIfGDFsGAdumO1yb1j
            lhQgXeHhkj+zIo4EoEGDdoRxrP4H3cbaRVh/MYDm0RlDbG75OUwRV23XJSY/qn2O
            7SRlJjhPQGxPoRRtpj4+3CsUm7yyBtfIXCNe6hHqkTvWbHNk3JLo7iUEq7omhT44
            6KyB3XrT0n7x6mh7yooJYEGLFcqhGFDfgPtzHFp9D6ZIagBzcel5DTKGWYR6ZWkx
            D+X9R6aZv8Qa98eAxk8Jq4S64j1SGBTMhOsMrqAqnSdUd5s1Cx4WzatKLwKl38fU
            aAEJAhCy9vaYcd5pvENB8lOLk9dMV93BwLsBvKCOWzW0qp0RsQ7hCcxdqd41tX7c
            2WVWwQbU1XXDcNRc+P+p/uG6AeUbUBWMhJaMzCiWJrQ8Ekw4qx2qquAH2KSq8pjB
            G3rpKIc49BZT
            =bGvR
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
