apiVersion: v1
kind: Secret
metadata:
    name: gradus-gtm-agent-secrets
    namespace: gradus-gtm
type: Opaque
stringData:
    PI_SECRETS: ENC[AES256_GCM,data:GmvTpVgX+NnK6a0hw4Fst5V4M5Vl6tfOpsFygztRDf+2uTWZ3ZocPAWyy/9TLxdcvs+7mXAj71Ac7MS8SjsXvEG+8uMZFgmA500U308siGmYe69K+GbgpdssAPHqxbv4uHkNPM+t14xSnUGxDr6Mx+TNfhCob1VBbLD52yaCnX77o9KTi67awlMDgGVAovaEhbOCc1u2lenysmP90kBgodKeb4nRsM/AKENsbgemLKVKffK1h0YsjbR22b6nWcSF3meHD71iCyKpynYRgIR4wu9B0yiGhN1H46tp6AbXcrn39gsCuX3NGV6cfUG4X/RIqJRLW8on4Fziwp585nl6nbxjiJQv6s+FYnnUu6Gr9gUAuQPeJBFRldCb47PuJq6y3inhLMPBMGIdb7gXi6T1D7aopZvGomy4lUsEovauBJbjpdVoVAj/xaxhhXOxztxNpNPNLkMcJ3v4xEUSc4NfaWdXt9+fdU2OsGxDlxDsXC77KnirJyDBcxpdvnf3q/8dPnD4MexvZokDNLs6kXsMaoo27/DvJoEDRSWB7SH+esuiApyUsta55uLJd77Tp3VR+shkuQOLg6gRJ4yvT1tzfjclXkovICdnEuHxLf2AfqLwttKoN8SshB9ZlFO68EtrfO+krwvRKY8uKVa4HqfUAFN2ej4mmfecYZhNVOWKqOkIzM4ejUvN5vkBLQ==,iv:BhGfEpF/mocoRuGHm255XT+eBChJxjTDMNHlXCI1PtI=,tag:bCWBcGIHfswUUm2pIMQerw==,type:str]
    git-credentials: ENC[AES256_GCM,data:yy370dstKBTozOXblaFLsgyzuGm98DmdOddNG9MAopxWmAI23l7iqEmmxJnKuR01017tMQy5t3tvR0nX6tyy9MsoogG3qXIMXb9KOOJ9WPtVuX/H9eY=,iv:cEbmcKUqyLg2hK05AQXRVmghN9ZkzNJUbtVXdsG4Ruc=,tag:pX6i0EFV/ZeEFKVGxiO9mg==,type:str]
    PI_TELEGRAM_CONFIG: ENC[AES256_GCM,data:zsxNsgnd/D7SJMvS6YN9SEtkKg8NTumCWCWDDFUyVrNMRNi2ET4ZtV/7qqV98F8bjYA+eGSKAhyMku61qqml8BEW9Uf6idwAD8m5uPxR4iIlhY2hkR7j7WbTkROz3Rfhn4l/NiE27pGf2q8WdNV4N+tDTEds+y0+AHe5EKNA7XlEouT5gyZNUUYv,iv:0YwhFqs5LCk2RBPya0yD0cOOhMPeiha84ApRZJyuvSw=,tag:LCYu1qPzRhf5xnOI6wqIeg==,type:str]
    coding-agent-config.json: ENC[AES256_GCM,data:WwL/V30T6UmYfM0FpbjQoVEtteiTqccJdDXmiZn/70pDbBatQIQzjPA78iQvs8hulZhR/RpCONlQBH52BIyegyiiemEbonGgOTKFnqU2XRIJN9vsHOMi+rCHG+xMEdpqp2xAdIo1xNHrEZhCEaeHd8cTdRYMV+jayGB8jFWsmCnzh7xJ4SiX7hM0LDByZ1Hx9rPtzzGImhm4C8kyYPP+X64mSCoN2qa2Cg3DnoYsGrjZoPYOOHOuKSuhqnNR4UecACl8aT9z3OC4OJmRrA60vp2vh6S2+yHUsTsjrVKh5ZxtbNGKYrpmdh9voZLvh5k6hqTAaukwyeW02O5LqeWXXGHlglDhl07keTh6gdXZ+I6Rfel2RmYlweaMkXpQfrI7cdaAd8FP+FgNVGC00rQVW7TZOXMr6KbDEVqE2lGYawzPSa4CInUJKAamX/dZca0Uy0r3djPZXZRAWsSRtCrd2ffMiFvIS9LDmsBJFahWQ3YtJhcQ2iie16ozpCfoAc8EfvyLE7lRexwsxTrIg+e1gRZb4et8roA1SWYMtYNP5GBQo7V3nyZF+heshFwdbeC6jgEzcv2O663jiQ7alHphE7Pd9ZQIL8wbFqxapQjqFU4IPjWl/2+afERUsS8Qwub1op74+e3TxJJiZ7O/wB3w0oUNJuy2MvvvM67v44sTzLGcq6unFrhT5qFSyAWajc8ijBZOiIJtF1gP66ySMnI9uHG/5QDRfXHo3ttWETjdwaWs4PvZZbXtV0lECrMlt2CpWQNBFmZnf1jVlCfTvza9FaXDqOM7AM01z3gCnZwnOPkRSPG/mHp3XXR2atSaZHLqkQsvlkni8NhADCI=,iv:Xkdtow+UwKOukPZSJrWQXzE80z//OAYeJCh1ssoQp9c=,tag:hf6ukGdh2zydCYwisyzUMA==,type:str]
sops:
    lastmodified: "2026-10-02T04:10:50Z"
    mac: ENC[AES256_GCM,data:Obj3xQuubZb/o7w2BHDaGeiaOOZDZTqj2VXu1f3+66zddReNRjvXHhYyBeZsfB8JPe8U7TG4iLCLU6p2LJm1x775sIajSJUf+ByLj3AkC4xHLqkrE/NlCQOaM2MKJt0zXkCTH1aIMktYCWXSQSlXH9JkdX2ldY28KeWHJUBptxY=,iv:RG4838+5SIwzEcqosuvx85sNW9rlsZrIJjTd6Ch+qcQ=,tag:xhy5s0BXQWa3My1Xgd1E8Q==,type:str]
    pgp:
        - created_at: "2026-09-30T05:55:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XAQ/9GZJlPeJPKE/weEk86fxAXnZlxVIekvvog7mZ7zt6wzS5
            WbD2EYMI3tIdqv8YnvNQ/Y9Bcsqv0YkxHBSSPfB1FcxTaEwWU27LqRvjiAfh+Fg8
            b+eHbVC9AGoc0++o1beKEHs4Ab9a8BqlEZB5hT/D+gxhhTLtOdP1z0E5jf239q0l
            +EH5QGmwa0ZmeAXjibkBx/wMnAf9b80pux4h4/WRDzFcPkfPks1eSWGEBfMyFhSj
            GoF3uV2cMql37RLLMqc31wv4Cf98bzFfX4EsQPdrYhXRSBdNIDkH5KAn9KumEBpe
            L02vO4QQTeC15Nf6ypXoyqEzVEIicIy0014SZ7e4x5RYPfhGGz31ZEErXFW8bxa7
            fc95OrNoqldohEsDaUHfsgnwF7S+nlw2isfFyYVFuZTKZ9iIfGDFsGAdumO1yb1j
            lhQgXeHhkj+zIo4EoEGDdoRxrP4H3cbaRVh/MYDm0RlDbG75OUwRV23XJSY/qn2O
            7SRlJjhPQGxPoRRtpj4+3CsUm7yyBtfIXCNe6hHqkTvWbHNk3JLo7iUEq7omhT44
            6KyB3XrT0n7x6mh7yooJYEGLFcqhGFDfgPtzHFp9D6ZIagBzcel5DTKGWYR6ZWkx
            D+X9R6aZv8Qa98eAxk8Jq4S64j1SGBTMhOsMrqAqnSdUd5s1Cx4WzatKLwKl38fU
            aAEJAhCy9vaYcd5pvENB8lOLk9dMV93BwLsBvKCOWzW0qp0RsQ7hCcxdqd41tX7c
            2WVWwQbU1XXDcNRc+P+p/uG6AeUbUBWMhJaMzCiWJrQ8Ekw4qx2qquAH2KSq8pjB
            G3rpKIc49BZT
            =bGvR
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
