apiVersion: v1
kind: Secret
metadata:
    name: gradus-gtm-agent-secrets
    namespace: gradus-gtm
type: Opaque
stringData:
    PI_SECRETS: ENC[AES256_GCM,data:GmvTpVgX+NnK6a0hw4Fst5V4M5Vl6tfOpsFygztRDf+2uTWZ3ZocPAWyy/9TLxdcvs+7mXAj71Ac7MS8SjsXvEG+8uMZFgmA500U308siGmYe69K+GbgpdssAPHqxbv4uHkNPM+t14xSnUGxDr6Mx+TNfhCob1VBbLD52yaCnX77o9KTi67awlMDgGVAovaEhbOCc1u2lenysmP90kBgodKeb4nRsM/AKENsbgemLKVKffK1h0YsjbR22b6nWcSF3meHD71iCyKpynYRgIR4wu9B0yiGhN1H46tp6AbXcrn39gsCuX3NGV6cfUG4X/RIqJRLW8on4Fziwp585nl6nbxjiJQv6s+FYnnUu6Gr9gUAuQPeJBFRldCb47PuJq6y3inhLMPBMGIdb7gXi6T1D7aopZvGomy4lUsEovauBJbjpdVoVAj/xaxhhXOxztxNpNPNLkMcJ3v4xEUSc4NfaWdXt9+fdU2OsGxDlxDsXC77KnirJyDBcxpdvnf3q/8dPnD4MexvZokDNLs6kXsMaoo27/DvJoEDRSWB7SH+esuiApyUsta55uLJd77Tp3VR+shkuQOLg6gRJ4yvT1tzfjclXkovICdnEuHxLf2AfqLwttKoN8SshB9ZlFO68EtrfO+krwvRKY8uKVa4HqfUAFN2ej4mmfecYZhNVOWKqOkIzM4ejUvN5vkBLQ==,iv:BhGfEpF/mocoRuGHm255XT+eBChJxjTDMNHlXCI1PtI=,tag:bCWBcGIHfswUUm2pIMQerw==,type:str]
    git-credentials: ENC[AES256_GCM,data:uCckSi37b17sXb1lNonlkX0H8lu9947EwlZPSn9+EPwUMGHrT/IvEceZucpjJU1mbGunsHNge03YM1bp+kFszs3cxdbkPXyBj4to3B2kdNrQFe5ygjE=,iv:f6FEW5XdujoQNY2AopM2oyE9g4KaUL99dLhW2OPQQ78=,tag:G/nG4S091N7EkkfS3yU/hw==,type:str]
    PI_TELEGRAM_CONFIG: ENC[AES256_GCM,data:zsxNsgnd/D7SJMvS6YN9SEtkKg8NTumCWCWDDFUyVrNMRNi2ET4ZtV/7qqV98F8bjYA+eGSKAhyMku61qqml8BEW9Uf6idwAD8m5uPxR4iIlhY2hkR7j7WbTkROz3Rfhn4l/NiE27pGf2q8WdNV4N+tDTEds+y0+AHe5EKNA7XlEouT5gyZNUUYv,iv:0YwhFqs5LCk2RBPya0yD0cOOhMPeiha84ApRZJyuvSw=,tag:LCYu1qPzRhf5xnOI6wqIeg==,type:str]
    coding-agent-config.json: ENC[AES256_GCM,data:9stg1JBKg52ElZvOKXb4ejcpNSnGv9gWW5XgClwxmTowWEY91zLI5VfMGXt/nU/R4Rao3qMWmGHBwCG0VsbLrFTRAMZpmeCCXoSTnWx3RaqAzrvlnku86EMU5ogxIU36Cgb7gcZEe2rgXNWMDbDSJS02kCv/zyhTVCF5LJ48f7OSBvXsbWIcrau0X8G0KjscxN31MzmH6opK2UlJbHUENKYGEZ0fshhLAN4oF+uyeM9z17fwMNDJGYrsXSWTHunQudm9gcZ8wEKGJFrz64N1hBaSq/n24wQH/RFlMgdv5ZtdpBmeP9XyxvrBSjlPwmt3W6xHhhaeJ6/MW6YOsBJcOtIdPxYWs/DL8gMo2TJ9638faz2yFNfe6DGrdSN79WjHjMlwLkSCKX/aI92TMDbr01NNT0HghMcOuXeAfuDUMmJu3I4DCQnVQsC1V+f+T4Ql4AVh8kyh7r0XhazXg73yGGvw7PyIaZA7O2zMUzeoCBP7p0vrao3aHqNNKgMYXJw/RapL42T9jijhzP0mI9ZpdHJBgnkcEypz3zMOZjZlfZO64zRtZWI7L/67Kj6GwkdK6nbkAXHHN4PWi5+qbDCREOu6g7mT+4n0cxpPhkT6zJ+KuI/MTmHkavYijdAvK9xD6/pF0NIgei8UU1sIqJ3wxBskpXjpmxU3lBLdkC++Eiq0ToOfG9mVcfl6xkGXegSNoV/DNeIM3nJSfeYnw3FDurEn0rrzXL/GMOLALsNB+GbUaB2eN75I4dd2e2fCkoP8Z5vm2XQ=,iv:erYC+46zYkFkN0xPPQYgehIv8a+DuDcbQd32zm9BMxg=,tag:rFD/wMuD6pr56AFh7og/uA==,type:str]
sops:
    lastmodified: "2026-10-02T01:53:52Z"
    mac: ENC[AES256_GCM,data:ZUzLREtNINfx0wEORzO2RF/OFMRsK9RSf6KlHZq003YIKul4HQv4YwsjRx6X1tftBCSEhc4loVcGmF0milGjOE4KHNGLJZPfPaUA7s948BWAZ7U8ghdzNoZQN9FXj/iVPTpi1XIlNLmsLolAxn9XecsX1LOQ51YON7uS+jLqLmY=,iv:KgEaYQnGWECTESe7y3m53V8/mgtfAUgBNtND+4LJ4zw=,tag:GCJlW7bSQl03LocMktZwAA==,type:str]
    pgp:
        - created_at: "2026-09-30T05:55:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XAQ/9GZJlPeJPKE/weEk86fxAXnZlxVIekvvog7mZ7zt6wzS5
            WbD2EYMI3tIdqv8YnvNQ/Y9Bcsqv0YkxHBSSPfB1FcxTaEwWU27LqRvjiAfh+Fg8
            b+eHbVC9AGoc0++o1beKEHs4Ab9a8BqlEZB5hT/D+gxhhTLtOdP1z0E5jf239q0l
            +EH5QGmwa0ZmeAXjibkBx/wMnAf9b80pux4h4/WRDzFcPkfPks1eSWGEBfMyFhSj
            GoF3uV2cMql37RLLMqc31wv4Cf98bzFfX4EsQPdrYhXRSBdNIDkH5KAn9KumEBpe
            L02vO4QQTeC15Nf6ypXoyqEzVEIicIy0014SZ7e4x5RYPfhGGz31ZEErXFW8bxa7
            fc95OrNoqldohEsDaUHfsgnwF7S+nlw2isfFyYVFuZTKZ9iIfGDFsGAdumO1yb1j
            lhQgXeHhkj+zIo4EoEGDdoRxrP4H3cbaRVh/MYDm0RlDbG75OUwRV23XJSY/qn2O
            7SRlJjhPQGxPoRRtpj4+3CsUm7yyBtfIXCNe6hHqkTvWbHNk3JLo7iUEq7omhT44
            6KyB3XrT0n7x6mh7yooJYEGLFcqhGFDfgPtzHFp9D6ZIagBzcel5DTKGWYR6ZWkx
            D+X9R6aZv8Qa98eAxk8Jq4S64j1SGBTMhOsMrqAqnSdUd5s1Cx4WzatKLwKl38fU
            aAEJAhCy9vaYcd5pvENB8lOLk9dMV93BwLsBvKCOWzW0qp0RsQ7hCcxdqd41tX7c
            2WVWwQbU1XXDcNRc+P+p/uG6AeUbUBWMhJaMzCiWJrQ8Ekw4qx2qquAH2KSq8pjB
            G3rpKIc49BZT
            =bGvR
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
