apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-whisper-models
  namespace: home-whisper
  annotations:
    volume.kubernetes.io/selected-node: brenno-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
