apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: home-classifier
  namespace: home-classifier
spec:
  image: git.brennoflavio.com.br/brennoflavio/home-classifier
  interval: 5m
