apiVersion: batch/v1
kind: CronJob
metadata:
  name: google-smarthome-integration-calendar
  namespace: google-smarthome-integration
spec:
  schedule: "*/5 * * * *"
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: calendar-sync
            image: ghcr.io/brennoflavio/google-smart-home-integration:f59a28cf8b8284cdbcecbae3ba47679a4a5358cd
            command: ["python", "/app/calendar_sync.py"]
            resources:
              limits:
                cpu: 50m
                memory: 128Mi
              requests:
                cpu: 25m
                memory: 128Mi
            volumeMounts:
            - name: google-smarthome-integration-oauth
              mountPath: /var/secret
              readOnly: true
            - name: token
              mountPath: /var/token
            envFrom:
            - secretRef:
                name: google-smarthome-integration-secrets
          volumes:
          - name: google-smarthome-integration-oauth
            secret:
              secretName: google-smarthome-integration-oauth
          - name: token
            persistentVolumeClaim:
              claimName: token
