apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1m
  url: oci://registry-1.docker.io/bitnamicharts
  type: "oci"
