provider: aws
aws:
    region: sa-east-1
    zoneType: public
    preferCNAME: true
    zoneIDFilters:
        - Z09602182CS7HUQKW198W
sources:
    - ingress
    - crd
domainFilters:
    - brennoflavio.com.br
registry: txt
txtOwnerId: brennoflavio
txtPrefix: _externaldns
txtEncrypt:
    enabled: true
policy: sync
resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 10m
        memory: 64Mi
crd:
    create: true
extraArgs:
    managed-record-types: CNAME
    ingress-class: external-nginx
