- hosts: server
  roles:
    - ssh-public-key

- hosts: hostinger
  tasks:
    - name: Create multiple SSH forwarding services
      include_role:
        name: ssh-tunnel
      vars:
        service_name: "{{ item.service_name }}"
        service_description: "{{ item.service_description }}"
        tunnel_local_port: "{{ item.tunnel_local_port }}"
        tunnel_remote_port: "{{ item.tunnel_remote_port }}"
        tunnel_ssh_user: root
        tunnel_remote_host: brennoflavio.com.br
        tunnel_remote_ssh_port: 8822
      loop:
        - service_name: port_25_forward
          service_description: Forward port 25 to remote host
          tunnel_local_port: 25
          tunnel_remote_port: 8825
        - service_name: port_587_forward
          service_description: Forward port 587 to remote host
          tunnel_local_port: 587
          tunnel_remote_port: 8587
        - service_name: port_110_forward
          service_description: Forward port 110 to remote host
          tunnel_local_port: 110
          tunnel_remote_port: 8110
        - service_name: port_143_forward
          service_description: Forward port 143 to remote host
          tunnel_local_port: 143
          tunnel_remote_port: 8143
        - service_name: port_465_forward
          service_description: Forward port 465 to remote host
          tunnel_local_port: 465
          tunnel_remote_port: 8465
        - service_name: port_995_forward
          service_description: Forward port 995 to remote host
          tunnel_local_port: 995
          tunnel_remote_port: 8995
        - service_name: port_993_forward
          service_description: Forward port 993 to remote host
          tunnel_local_port: 993
          tunnel_remote_port: 8993
