---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-video-frame-extractor
  namespace: nextcloud-video-frame-extractor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
