---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
    name: frontend
    namespace: "minatto-1-preview"
spec:
    image: ghcr.io/brennoflavio/minatto-frontend
    interval: 1m0s
    secretRef:
      name: gcr-secret
