apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  releaseName: rancher
  chart:
    spec:
      chart: rancher
      version: 2.12.0
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: cattle-system
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    hostname: "kubernetes.brennoflavio.com.br"
    bootstrapPassword: "admin-password"
    ingress:
      tls:
        source: secret
      extraAnnotations:
        cert-manager.io/cluster-issuer: lets-encrypt
        external-dns.alpha.kubernetes.io/target: "brennoflavio.com.br"
    privateCA: false
    replicas: 1
