apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
  namespace: influx
  annotations:
    volume.kubernetes.io/selected-node: brenno-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
