apiVersion: v1
kind: Secret
metadata:
    name: influxdb-init
    namespace: influx
type: Opaque
stringData:
    DOCKER_INFLUXDB_INIT_MODE: ENC[AES256_GCM,data:hmrfssM=,iv:cHD4FFslr8Rep+XcOBSWicXDMJS9jgsK2EtMPFAdt+U=,tag:+a2Lnf/Jh23ItShiH84bSw==,type:str]
    DOCKER_INFLUXDB_INIT_USERNAME: ENC[AES256_GCM,data:IqalE9g=,iv:PGBZn7hnhtdrtT7zA7WMQEVAXP6wxwBjHC6eeGJet0c=,tag:KhniVikOcCJh4ttnN4+b5w==,type:str]
    DOCKER_INFLUXDB_INIT_PASSWORD: ENC[AES256_GCM,data:id5OubLsxm4NBEqtBfSBM3jO81mP8CDBwbl0aRtCBqk=,iv:x83kYRgMFue+3U9djPAdtWhRMlOblNXkQAGVq3TPE1g=,tag:zOSyDP9wC0ZqyRlLeXm4bA==,type:str]
    DOCKER_INFLUXDB_INIT_ORG: ENC[AES256_GCM,data:lOoGsvg6xyqRHlMu,iv:t2aSmydyI+jeNxCefkS7M2q/1u6lXVf+gLNfpTD5iE8=,tag:qJVn1y3woVVXrp7nLnOX6g==,type:str]
    DOCKER_INFLUXDB_INIT_BUCKET: ENC[AES256_GCM,data:fm9mWicdOw==,iv:fEhFswy8dDz827ZOeM9w3zkkhFK4m9BiHbl3dozHNmk=,tag:kTIEpdZcMwmTme5j6llj+w==,type:str]
    DOCKER_INFLUXDB_INIT_RETENTION: ENC[AES256_GCM,data:zmkP,iv:8ARYKLx/QhU137COvZx3UKshJADMYH99HXvfFL6fhR4=,tag:VgGrx1kA+yNlZ/iEYfycrA==,type:str]
    DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ENC[AES256_GCM,data:lCKh995vfXsI4YFN8q3VmSI/4ilkD2rHHOPjXOmxwEs=,iv:60kBFbcGWHcGu8fEPZri02dEGpwSMM7PBYV42mWDoM8=,tag:lJ0+hFcM+cP9UBB/jEajWw==,type:str]
sops:
    lastmodified: "2026-09-09T14:45:38Z"
    mac: ENC[AES256_GCM,data:wHPqGzMrFXLslwc6N4MMEGwQwtPT5s8TKAmLMn/dwieGYVgFszDOJ31QMWEExcGn7w2zxUOA0Dyr7PqmIBLE/DW/ywsF76MukMvu7zNhpEDo9nh8zlwLqHXHbZy/leZNopim/B1Hb2PZvmqhYU3yvLdsVkyBly6YFNgekhY3eDI=,iv:nTo6I4Wnn7SuE2wAc2puWabqBnYiwIWKhwkXElJxA5g=,tag:E1FVz7u0BTUQnaKLso+cbw==,type:str]
    pgp:
        - created_at: "2026-09-09T14:45:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XAQ//dLhg83BEIoHqPGtnwgYODoJca4d7IsVjhSAQScHrd+u6
            DU0rKtQpKimlG5uKvP6ZQ+/QFJu9l/niHvjG8RqD3IH3VUCrILBO8o35VV7bLoYs
            obo+bJelqDIGLjxsYhoAevXOsQh8jQZaHRf3GrQQzD95wURpHOnwvNxnFnSAKxqG
            HgXeenO2Pniwao2X5KXLPa60mIpLyhbbVwLByJjdibM9yx4CCmHdF6yAo3TrS4Z4
            ZhFPjCcvocYVnRiiKl1Z4ceqC+mCeV26/5Hb0+IhYXwHJ6Qyfv/bvYWdH3vkk/LX
            1FJjG59PcBxz3gbRynAqVOc9jzOb3amYOz/4krBLhC59Ymlfct/MSh5dTxSPKaEp
            NNmQvX2KPz/8Upq+Lg8Vr2/F+uXlAFDwrw1NXvpdleu022e+N8OJ3/L7SvGgS3Q1
            B3keL2L98VBgwSrAfkk8w1fhEq4FIGKRuJvIIfcJANUtHA9cfdr6b/GU6OxA6HeG
            xBjLZ/nZhD8WC2+znHEaUEC/S7nVIAYCOpHZWyLECnh7mNvURv5/kpRRnCq7u2ex
            2Qd3VPaTsqSqTxNbeabtXshBnHaEvZH1r7olW8x7TqPO/uVPAFRZpXTFOjJT7aam
            0P9GVqo1BLLvROVFMeUHLlKVeu9yy95yfA/RLe1QWlw3tLkCa/qifMFQkPxFi2jU
            aAEJAhC6Rin708PgrLbz6wdR2pW+QVzZ5A5Z879LBaeZ/KuLsBclgELEebE3qZfx
            p2XxEernSXcZzGzsMMOmc49DvHUHPhbdkZwumgtW9W0pPvvsZvmVj5TSFD1XszFb
            E6w0AKhblWZW
            =m3nH
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
