apiVersion: v1
kind: Secret
metadata:
    name: sitio-secrets
    namespace: sitio
stringData:
    FILE_PATH: ENC[AES256_GCM,data:YJpUhP+a/J3njyg5XV56n6+2ePG747a3,iv:ZMoae4gx1ZRGGBptN88KH2YxrmFe+Fc2DKuDCJd29WU=,tag:ZedmuXGoLOKk2noF4FlPPA==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:7RJWBr1N1OA=,iv:PAtrlnTaSrASS6nYM+rUUwnWQQVu7daDdKE4TNTbC6g=,tag:2KowSrHcG+PNFKhiyy0Jqg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:/G9t+bhjzcs=,iv:aDZoyOA2yMWPD37eWfwAf38oR7+1xRA2brxaEOT/is0=,tag:xWCnImIinM2/aj0C6B5uPQ==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:ARF8a/puQWQJigF7Ciyan5X2QPTlrKwK,iv:h9T2WHpe7PeiVgHcFBMYz1uuEgDd/mf8XRqDYwnQrPc=,tag:LsN+TjHo/osJWq2F2Ryb+Q==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:tpM8,iv:j+8vnPBviV8I+wOgMtkhx81wgR1RviYxdWw9UGFkNYw=,tag:lMjqD2gDuD9yPwRJBq+nfQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:J6RAKUrJTnuhdajb7IWdkUfj1AHnHw==,iv:7L1Bso/GAZpA+3F9R6hksXD95o8kwcVbJpMXBU8XPss=,tag:r7PUPtgtfkiwbqAqC3KE2Q==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:kbx9wkZOmCX/e9r7hko=,iv:s04sF82olIw6YeZLX7kqMsQ6l/0s8Rncha1oHp9g95o=,tag:CSvp4MGPBBdS/NFofG6qYA==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:46uT4U3nwSWXl98mK6uFaPkEMHYmDg==,iv:EO7Ztiu0VmMRWbZB/1tW+oHkswHzZmUKIhQwg2qtzfY=,tag:sbYPqi8XxZMrMjgPNu1/Sg==,type:str]
    SMTP_TO: ENC[AES256_GCM,data:eesdisbAjuZN3UJU9bZzAupM5buf0rLS8IA2O+tfR7SbLutzxz3xNH5jq1wT1oNEWyoPBUlY,iv:i1ph1HJLhdA5XeEqLknW9T0Akl44udx1tikmUHIA9Ig=,tag:rbFLHF2vBlZZy6kzhpkU1A==,type:str]
sops:
    lastmodified: "2026-09-13T05:39:56Z"
    mac: ENC[AES256_GCM,data:a6m6Ebw/BdLuSQ9/N/UdZXUnP2+Auoe51L03FTLp9zUDYHNwsTydFxxpBYqVuXUcY7rBEtzGdRS2e85KCXRM2QJ3Txyktl1wJt52HFXqVXwy6bSmbHZ07d0Xr6lS3REpl46UMfSDc8IMtLwWkSvxYdXZ/9KwN4G4OnGy45FKgg8=,iv:tal3qibRiT2P3wGAIc3a5MZB0Cd1/f5Bk45lu0tkGyo=,tag:CeNf/HOyWWCn/OoarzLalA==,type:str]
    pgp:
        - created_at: "2026-09-13T05:39:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XARAAi3lqv4ViCQJNK+ZFTk6M7oNsQsQnZ+USRZnVGcNN4wVo
            QCetBKTXNagpEDEHfPgT3khvWTBuLC3tHUmHJ/2kPEuQcCNU0GXYWkcFtOGnXegT
            n8iRAlVt4QpukAfe20cATFfG22ozGUjBSIsGIrxIGBnwM/U5uLNHAItoqCVZs3Sj
            v2qR+Ha1lbAeDjF8LE3Flnujo31ODvLwF8tx0gp4iNeMGyal9L9wFDnC9IuiwHzi
            OVsVB255bVlvR+m7lE5kABGJlJ6XrzTsbRhvkONEAFyellSYNuriofObRjCh4IdB
            GLJFFg+POCBAhggOa4/XmCkUzfU0wRWAyiQWBRMuWaHDkS2m7hNL8j9TtV6n+LqN
            hNnjqQDV/X+UrvgzL7BMUJ14B+fphPSaz+wqxu9uSkXeXlYzNSTHqm2aGZ188n1J
            9p55GkFRUksmrDbPZGLqhsqb7eoDfp6v6/IDib7S4JckKZxco/rLvfHvRECz208N
            AOs5B1n3vXgT/8R3Gv7K2pDg23CC/BN4F1GUmF/SbSReobphYcZ0jtlegBV6mnxt
            YWSQINAFsyCQpVelMhPwqvFsyFc4aagQFz1MLCtmwN0cUrSgwKKmlgVc5W4Cuubz
            6lTXk5/95d2cIIw2Exmjsoi+j8uqPU4WP154mfbbDcrKD3s6KRcawFuwiCTDCpfU
            aAEJAhD/ps62XTyD4Onw0h6NKqFwyEjupI3JpQ6gJ4WVVwM3s+efdYjTRwNkq8q0
            kBL9l6OtTEsgZHkCPpDfsOgSe8XPNPB3mf0BsbEaRTmDs9L6Gx1R52LvhJulMC+3
            XfF7IMXpCPPU
            =J3CO
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
